// BH67F2485.h
//	This file contains the definition of registers for
//		Holtek BH67F2485 microcontroller.
//	Generated by HTFileParse.dll.
//	[VERSION] 1.5, 4
// Do not modify manually.

#ifndef _BH67F2485_H_
#define _BH67F2485_H_

#ifndef __DISABLE_HGCC_BUILD_IN__
#include "build-in.h"
#endif

#define DEFINE_ISR(isr_name, vector) void __attribute((interrupt(vector))) isr_name(void)

#define DEFINE_SFR(sfr_type, sfr, addr) static volatile sfr_type sfr __attribute__ ((at(addr)))

typedef unsigned char __sfr_byte;

typedef struct {
	unsigned char __c : 1;
	unsigned char __ac : 1;
	unsigned char __z : 1;
	unsigned char __ov : 1;
	unsigned char __pdf : 1;
	unsigned char __to : 1;
	unsigned char __cz : 1;
	unsigned char __sc : 1;
} __status_bits;

typedef union {
	__status_bits bits;
	__sfr_byte byte;
} __status_type;

typedef struct {
	unsigned char __pbp0 : 1;
	unsigned char __pbp1 : 1;
	unsigned char __pbp2 : 1;
	unsigned char : 5;
} __pbp_bits;

typedef union {
	__pbp_bits bits;
	__sfr_byte byte;
} __pbp_type;

typedef struct {
	unsigned char __wrf : 1;
	unsigned char __lrf : 1;
	unsigned char __lvrf : 1;
	unsigned char __rstf : 1;
	unsigned char : 4;
} __rstfc_bits;

typedef union {
	__rstfc_bits bits;
	__sfr_byte byte;
} __rstfc_type;

typedef struct {
	unsigned char __fsiden : 1;
	unsigned char __fhiden : 1;
	unsigned char __fss : 1;
	unsigned char __fhs : 1;
	unsigned char : 1;
	unsigned char __cks0 : 1;
	unsigned char __cks1 : 1;
	unsigned char __cks2 : 1;
} __scc_bits;

typedef union {
	__scc_bits bits;
	__sfr_byte byte;
} __scc_type;

typedef struct {
	unsigned char __hircen : 1;
	unsigned char __hircf : 1;
	unsigned char __hirc0 : 1;
	unsigned char __hirc1 : 1;
	unsigned char : 4;
} __hircc_bits;

typedef union {
	__hircc_bits bits;
	__sfr_byte byte;
} __hircc_type;

typedef struct {
	unsigned char __hxten : 1;
	unsigned char __hxtf : 1;
	unsigned char __hxtm : 1;
	unsigned char : 5;
} __hxtc_bits;

typedef union {
	__hxtc_bits bits;
	__sfr_byte byte;
} __hxtc_type;

typedef struct {
	unsigned char __lxten : 1;
	unsigned char __lxtf : 1;
	unsigned char : 6;
} __lxtc_bits;

typedef union {
	__lxtc_bits bits;
	__sfr_byte byte;
} __lxtc_type;

typedef struct {
	unsigned char __pa0 : 1;
	unsigned char __pa1 : 1;
	unsigned char __pa2 : 1;
	unsigned char __pa3 : 1;
	unsigned char __pa4 : 1;
	unsigned char __pa5 : 1;
	unsigned char __pa6 : 1;
	unsigned char __pa7 : 1;
} __pa_bits;

typedef union {
	__pa_bits bits;
	__sfr_byte byte;
} __pa_type;

typedef struct {
	unsigned char __pac0 : 1;
	unsigned char __pac1 : 1;
	unsigned char __pac2 : 1;
	unsigned char __pac3 : 1;
	unsigned char __pac4 : 1;
	unsigned char __pac5 : 1;
	unsigned char __pac6 : 1;
	unsigned char __pac7 : 1;
} __pac_bits;

typedef union {
	__pac_bits bits;
	__sfr_byte byte;
} __pac_type;

typedef struct {
	unsigned char __papu0 : 1;
	unsigned char __papu1 : 1;
	unsigned char __papu2 : 1;
	unsigned char __papu3 : 1;
	unsigned char __papu4 : 1;
	unsigned char __papu5 : 1;
	unsigned char __papu6 : 1;
	unsigned char __papu7 : 1;
} __papu_bits;

typedef union {
	__papu_bits bits;
	__sfr_byte byte;
} __papu_type;

typedef struct {
	unsigned char __pawu0 : 1;
	unsigned char __pawu1 : 1;
	unsigned char __pawu2 : 1;
	unsigned char __pawu3 : 1;
	unsigned char __pawu4 : 1;
	unsigned char __pawu5 : 1;
	unsigned char __pawu6 : 1;
	unsigned char __pawu7 : 1;
} __pawu_bits;

typedef union {
	__pawu_bits bits;
	__sfr_byte byte;
} __pawu_type;

typedef struct {
	unsigned char __rstc0 : 1;
	unsigned char __rstc1 : 1;
	unsigned char __rstc2 : 1;
	unsigned char __rstc3 : 1;
	unsigned char __rstc4 : 1;
	unsigned char __rstc5 : 1;
	unsigned char __rstc6 : 1;
	unsigned char __rstc7 : 1;
} __rstc_bits;

typedef union {
	__rstc_bits bits;
	__sfr_byte byte;
} __rstc_type;

typedef struct {
	unsigned char __lvs0 : 1;
	unsigned char __lvs1 : 1;
	unsigned char __lvs2 : 1;
	unsigned char __lvs3 : 1;
	unsigned char __lvs4 : 1;
	unsigned char __lvs5 : 1;
	unsigned char __lvs6 : 1;
	unsigned char __lvs7 : 1;
} __lvrc_bits;

typedef union {
	__lvrc_bits bits;
	__sfr_byte byte;
} __lvrc_type;

typedef struct {
	unsigned char __vlvd0 : 1;
	unsigned char __vlvd1 : 1;
	unsigned char __vlvd2 : 1;
	unsigned char __vbgen : 1;
	unsigned char __lvden : 1;
	unsigned char __lvdo : 1;
	unsigned char : 2;
} __lvdc_bits;

typedef union {
	__lvdc_bits bits;
	__sfr_byte byte;
} __lvdc_type;

typedef struct {
	unsigned char __stmpe : 1;
	unsigned char __stmae : 1;
	unsigned char __ptm0pe : 1;
	unsigned char __ptm0ae : 1;
	unsigned char __stmpf : 1;
	unsigned char __stmaf : 1;
	unsigned char __ptm0pf : 1;
	unsigned char __ptm0af : 1;
} __mfi0_bits;

typedef union {
	__mfi0_bits bits;
	__sfr_byte byte;
} __mfi0_type;

typedef struct {
	unsigned char __ptm1pe : 1;
	unsigned char __ptm1ae : 1;
	unsigned char __ptm2pe : 1;
	unsigned char __ptm2ae : 1;
	unsigned char __ptm1pf : 1;
	unsigned char __ptm1af : 1;
	unsigned char __ptm2pf : 1;
	unsigned char __ptm2af : 1;
} __mfi1_bits;

typedef union {
	__mfi1_bits bits;
	__sfr_byte byte;
} __mfi1_type;

typedef struct {
	unsigned char __lve : 1;
	unsigned char __dee : 1;
	unsigned char __int4e : 1;
	unsigned char __int5e : 1;
	unsigned char __lvf : 1;
	unsigned char __def : 1;
	unsigned char __int4f : 1;
	unsigned char __int5f : 1;
} __mfi2_bits;

typedef union {
	__mfi2_bits bits;
	__sfr_byte byte;
} __mfi2_type;

typedef struct {
	unsigned char __ws0 : 1;
	unsigned char __ws1 : 1;
	unsigned char __ws2 : 1;
	unsigned char __we0 : 1;
	unsigned char __we1 : 1;
	unsigned char __we2 : 1;
	unsigned char __we3 : 1;
	unsigned char __we4 : 1;
} __wdtc_bits;

typedef union {
	__wdtc_bits bits;
	__sfr_byte byte;
} __wdtc_type;

typedef struct {
	unsigned char __int0s0 : 1;
	unsigned char __int0s1 : 1;
	unsigned char __int1s0 : 1;
	unsigned char __int1s1 : 1;
	unsigned char __int2s0 : 1;
	unsigned char __int2s1 : 1;
	unsigned char __int3s0 : 1;
	unsigned char __int3s1 : 1;
} __integ0_bits;

typedef union {
	__integ0_bits bits;
	__sfr_byte byte;
} __integ0_type;

typedef struct {
	unsigned char __emi : 1;
	unsigned char __int0e : 1;
	unsigned char __int1e : 1;
	unsigned char __ade : 1;
	unsigned char __int0f : 1;
	unsigned char __int1f : 1;
	unsigned char __adf : 1;
	unsigned char : 1;
} __intc0_bits;

typedef union {
	__intc0_bits bits;
	__sfr_byte byte;
} __intc0_type;

typedef struct {
	unsigned char __mf0e : 1;
	unsigned char __mf1e : 1;
	unsigned char __mf2e : 1;
	unsigned char __ovpe : 1;
	unsigned char __mf0f : 1;
	unsigned char __mf1f : 1;
	unsigned char __mf2f : 1;
	unsigned char __ovpf : 1;
} __intc1_bits;

typedef union {
	__intc1_bits bits;
	__sfr_byte byte;
} __intc1_type;

typedef struct {
	unsigned char __tb0e : 1;
	unsigned char __tb1e : 1;
	unsigned char __int2e : 1;
	unsigned char __int3e : 1;
	unsigned char __tb0f : 1;
	unsigned char __tb1f : 1;
	unsigned char __int2f : 1;
	unsigned char __int3f : 1;
} __intc2_bits;

typedef union {
	__intc2_bits bits;
	__sfr_byte byte;
} __intc2_type;

typedef struct {
	unsigned char __ur0e : 1;
	unsigned char __sime : 1;
	unsigned char __spie : 1;
	unsigned char __ur1e : 1;
	unsigned char __ur0f : 1;
	unsigned char __simf : 1;
	unsigned char __spif : 1;
	unsigned char __ur1f : 1;
} __intc3_bits;

typedef union {
	__intc3_bits bits;
	__sfr_byte byte;
} __intc3_type;

typedef struct {
	unsigned char __pb0 : 1;
	unsigned char __pb1 : 1;
	unsigned char __pb2 : 1;
	unsigned char __pb3 : 1;
	unsigned char : 4;
} __pb_bits;

typedef union {
	__pb_bits bits;
	__sfr_byte byte;
} __pb_type;

typedef struct {
	unsigned char __pbc0 : 1;
	unsigned char __pbc1 : 1;
	unsigned char __pbc2 : 1;
	unsigned char __pbc3 : 1;
	unsigned char : 4;
} __pbc_bits;

typedef union {
	__pbc_bits bits;
	__sfr_byte byte;
} __pbc_type;

typedef struct {
	unsigned char __pbpu0 : 1;
	unsigned char __pbpu1 : 1;
	unsigned char __pbpu2 : 1;
	unsigned char __pbpu3 : 1;
	unsigned char : 4;
} __pbpu_bits;

typedef union {
	__pbpu_bits bits;
	__sfr_byte byte;
} __pbpu_type;

typedef struct {
	unsigned char __pc0 : 1;
	unsigned char __pc1 : 1;
	unsigned char __pc2 : 1;
	unsigned char __pc3 : 1;
	unsigned char __pc4 : 1;
	unsigned char __pc5 : 1;
	unsigned char __pc6 : 1;
	unsigned char __pc7 : 1;
} __pc_bits;

typedef union {
	__pc_bits bits;
	__sfr_byte byte;
} __pc_type;

typedef struct {
	unsigned char __pcc0 : 1;
	unsigned char __pcc1 : 1;
	unsigned char __pcc2 : 1;
	unsigned char __pcc3 : 1;
	unsigned char __pcc4 : 1;
	unsigned char __pcc5 : 1;
	unsigned char __pcc6 : 1;
	unsigned char __pcc7 : 1;
} __pcc_bits;

typedef union {
	__pcc_bits bits;
	__sfr_byte byte;
} __pcc_type;

typedef struct {
	unsigned char __pcpu0 : 1;
	unsigned char __pcpu1 : 1;
	unsigned char __pcpu2 : 1;
	unsigned char __pcpu3 : 1;
	unsigned char __pcpu4 : 1;
	unsigned char __pcpu5 : 1;
	unsigned char __pcpu6 : 1;
	unsigned char __pcpu7 : 1;
} __pcpu_bits;

typedef union {
	__pcpu_bits bits;
	__sfr_byte byte;
} __pcpu_type;

typedef struct {
	unsigned char __int4s0 : 1;
	unsigned char __int4s1 : 1;
	unsigned char __int5s0 : 1;
	unsigned char __int5s1 : 1;
	unsigned char : 4;
} __integ1_bits;

typedef union {
	__integ1_bits bits;
	__sfr_byte byte;
} __integ1_type;

typedef struct {
	unsigned char __clksel0 : 1;
	unsigned char __clksel1 : 1;
	unsigned char : 6;
} __pscr_bits;

typedef union {
	__pscr_bits bits;
	__sfr_byte byte;
} __pscr_type;

typedef struct {
	unsigned char __tb00 : 1;
	unsigned char __tb01 : 1;
	unsigned char __tb02 : 1;
	unsigned char : 4;
	unsigned char __tb0on : 1;
} __tb0c_bits;

typedef union {
	__tb0c_bits bits;
	__sfr_byte byte;
} __tb0c_type;

typedef struct {
	unsigned char __tb10 : 1;
	unsigned char __tb11 : 1;
	unsigned char __tb12 : 1;
	unsigned char : 4;
	unsigned char __tb1on : 1;
} __tb1c_bits;

typedef union {
	__tb1c_bits bits;
	__sfr_byte byte;
} __tb1c_type;

typedef struct {
	unsigned char __txif0 : 1;
	unsigned char __tidle0 : 1;
	unsigned char __rxif0 : 1;
	unsigned char __ridle0 : 1;
	unsigned char __oerr0 : 1;
	unsigned char __ferr0 : 1;
	unsigned char __nf0 : 1;
	unsigned char __perr0 : 1;
} __u0sr_bits;

typedef union {
	__u0sr_bits bits;
	__sfr_byte byte;
} __u0sr_type;

typedef struct {
	unsigned char __tx80 : 1;
	unsigned char __rx80 : 1;
	unsigned char __txbrk0 : 1;
	unsigned char __stops0 : 1;
	unsigned char __prt0 : 1;
	unsigned char __pren0 : 1;
	unsigned char __bno0 : 1;
	unsigned char __uarten0 : 1;
} __u0cr1_bits;

typedef union {
	__u0cr1_bits bits;
	__sfr_byte byte;
} __u0cr1_type;

typedef struct {
	unsigned char __teie0 : 1;
	unsigned char __tiie0 : 1;
	unsigned char __rie0 : 1;
	unsigned char __wake0 : 1;
	unsigned char __adden0 : 1;
	unsigned char __brgh0 : 1;
	unsigned char __rxen0 : 1;
	unsigned char __txen0 : 1;
} __u0cr2_bits;

typedef union {
	__u0cr2_bits bits;
	__sfr_byte byte;
} __u0cr2_type;

typedef struct {
	unsigned char __txrx00 : 1;
	unsigned char __txrx01 : 1;
	unsigned char __txrx02 : 1;
	unsigned char __txrx03 : 1;
	unsigned char __txrx04 : 1;
	unsigned char __txrx0 : 1;
	unsigned char __txrx06 : 1;
	unsigned char __txrx07 : 1;
} __txr_rxr0_bits;

typedef union {
	__txr_rxr0_bits bits;
	__sfr_byte byte;
} __txr_rxr0_type;

typedef struct {
	unsigned char __brg00 : 1;
	unsigned char __brg01 : 1;
	unsigned char __brg02 : 1;
	unsigned char __brg03 : 1;
	unsigned char __brg04 : 1;
	unsigned char __brg05 : 1;
	unsigned char __brg06 : 1;
	unsigned char __brg07 : 1;
} __brg0_bits;

typedef union {
	__brg0_bits bits;
	__sfr_byte byte;
} __brg0_type;

typedef struct {
	unsigned char __simicf : 1;
	unsigned char __simen : 1;
	unsigned char __simdeb0 : 1;
	unsigned char __simdeb1 : 1;
	unsigned char : 1;
	unsigned char __sim0 : 1;
	unsigned char __sim1 : 1;
	unsigned char __sim2 : 1;
} __simc0_bits;

typedef union {
	__simc0_bits bits;
	__sfr_byte byte;
} __simc0_type;

typedef struct {
	unsigned char __rxak : 1;
	unsigned char __iamwu : 1;
	unsigned char __srw : 1;
	unsigned char __txak : 1;
	unsigned char __htx : 1;
	unsigned char __hbb : 1;
	unsigned char __haas : 1;
	unsigned char __hcf : 1;
} __simc1_bits;

typedef union {
	__simc1_bits bits;
	__sfr_byte byte;
} __simc1_type;

typedef struct {
	unsigned char : 1;
	unsigned char __sima0 : 1;
	unsigned char __sima1 : 1;
	unsigned char __sima2 : 1;
	unsigned char __sima3 : 1;
	unsigned char __sima4 : 1;
	unsigned char __sima5 : 1;
	unsigned char __sima6 : 1;
} __sima_bits;

typedef union {
	__sima_bits bits;
	__sfr_byte byte;
} __sima_type;

typedef struct {
	unsigned char __trf : 1;
	unsigned char __wcol : 1;
	unsigned char __csen : 1;
	unsigned char __mls : 1;
	unsigned char __ckeg : 1;
	unsigned char __ckpolb : 1;
	unsigned char : 2;
} __simc2_bits;

typedef union {
	__simc2_bits bits;
	__sfr_byte byte;
} __simc2_type;

typedef struct {
	unsigned char __simtos0 : 1;
	unsigned char __simtos1 : 1;
	unsigned char __simtos2 : 1;
	unsigned char __simtos3 : 1;
	unsigned char __simtos4 : 1;
	unsigned char __simtos5 : 1;
	unsigned char __simtof : 1;
	unsigned char __simtoen : 1;
} __simtoc_bits;

typedef union {
	__simtoc_bits bits;
	__sfr_byte byte;
} __simtoc_type;

typedef struct {
	unsigned char __spiicf : 1;
	unsigned char __spien : 1;
	unsigned char : 3;
	unsigned char __spim0 : 1;
	unsigned char __spim1 : 1;
	unsigned char __spim2 : 1;
} __spic0_bits;

typedef union {
	__spic0_bits bits;
	__sfr_byte byte;
} __spic0_type;

typedef struct {
	unsigned char __spitrf : 1;
	unsigned char __spiwcol : 1;
	unsigned char __spicsen : 1;
	unsigned char __spimls : 1;
	unsigned char __spickeg : 1;
	unsigned char __spickpolb : 1;
	unsigned char : 2;
} __spic1_bits;

typedef union {
	__spic1_bits bits;
	__sfr_byte byte;
} __spic1_type;

typedef struct {
	unsigned char __ovpdeb0 : 1;
	unsigned char __ovpdeb1 : 1;
	unsigned char __ovpvrs : 1;
	unsigned char : 1;
	unsigned char __ovpchy : 1;
	unsigned char __ovpen : 1;
	unsigned char : 2;
} __ovpc0_bits;

typedef union {
	__ovpc0_bits bits;
	__sfr_byte byte;
} __ovpc0_type;

typedef struct {
	unsigned char __ovpcof0 : 1;
	unsigned char __ovpcof1 : 1;
	unsigned char __ovpcof2 : 1;
	unsigned char __ovpcof3 : 1;
	unsigned char __ovpcof4 : 1;
	unsigned char __ovpcrs : 1;
	unsigned char __ovpcofm : 1;
	unsigned char __ovpo : 1;
} __ovpc1_bits;

typedef union {
	__ovpc1_bits bits;
	__sfr_byte byte;
} __ovpc1_type;

typedef struct {
	unsigned char __eea0 : 1;
	unsigned char __eea1 : 1;
	unsigned char __eea2 : 1;
	unsigned char __eea3 : 1;
	unsigned char __eea4 : 1;
	unsigned char __eea5 : 1;
	unsigned char __eea6 : 1;
	unsigned char : 1;
} __eea_bits;

typedef union {
	__eea_bits bits;
	__sfr_byte byte;
} __eea_type;

typedef struct {
	unsigned char __txif1 : 1;
	unsigned char __tidle1 : 1;
	unsigned char __rxif1 : 1;
	unsigned char __ridle1 : 1;
	unsigned char __oerr1 : 1;
	unsigned char __ferr1 : 1;
	unsigned char __nf1 : 1;
	unsigned char __perr1 : 1;
} __u1sr_bits;

typedef union {
	__u1sr_bits bits;
	__sfr_byte byte;
} __u1sr_type;

typedef struct {
	unsigned char __tx81 : 1;
	unsigned char __rx81 : 1;
	unsigned char __txbrk1 : 1;
	unsigned char __stops1 : 1;
	unsigned char __prt1 : 1;
	unsigned char __pren1 : 1;
	unsigned char __bno1 : 1;
	unsigned char __uarten1 : 1;
} __u1cr1_bits;

typedef union {
	__u1cr1_bits bits;
	__sfr_byte byte;
} __u1cr1_type;

typedef struct {
	unsigned char __teie1 : 1;
	unsigned char __tiie1 : 1;
	unsigned char __rie1 : 1;
	unsigned char __wake1 : 1;
	unsigned char __adden1 : 1;
	unsigned char __brgh1 : 1;
	unsigned char __rxen1 : 1;
	unsigned char __txen1 : 1;
} __u1cr2_bits;

typedef union {
	__u1cr2_bits bits;
	__sfr_byte byte;
} __u1cr2_type;

typedef struct {
	unsigned char __txrx10 : 1;
	unsigned char __txrx11 : 1;
	unsigned char __txrx12 : 1;
	unsigned char __txrx13 : 1;
	unsigned char __txrx14 : 1;
	unsigned char __txrx15 : 1;
	unsigned char __txrx16 : 1;
	unsigned char __txrx17 : 1;
} __txr_rxr1_bits;

typedef union {
	__txr_rxr1_bits bits;
	__sfr_byte byte;
} __txr_rxr1_type;

typedef struct {
	unsigned char __brg10 : 1;
	unsigned char __brg11 : 1;
	unsigned char __brg12 : 1;
	unsigned char __brg13 : 1;
	unsigned char __brg14 : 1;
	unsigned char __brg15 : 1;
	unsigned char __brg16 : 1;
	unsigned char __brg17 : 1;
} __brg1_bits;

typedef union {
	__brg1_bits bits;
	__sfr_byte byte;
} __brg1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __ston : 1;
	unsigned char __stck0 : 1;
	unsigned char __stck1 : 1;
	unsigned char __stck2 : 1;
	unsigned char __stpau : 1;
} __stmc0_bits;

typedef union {
	__stmc0_bits bits;
	__sfr_byte byte;
} __stmc0_type;

typedef struct {
	unsigned char __stcclr : 1;
	unsigned char __stdpx : 1;
	unsigned char __stpol : 1;
	unsigned char __stoc : 1;
	unsigned char __stio0 : 1;
	unsigned char __stio1 : 1;
	unsigned char __stm0 : 1;
	unsigned char __stm1 : 1;
} __stmc1_bits;

typedef union {
	__stmc1_bits bits;
	__sfr_byte byte;
} __stmc1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt0on : 1;
	unsigned char __pt0ck0 : 1;
	unsigned char __pt0ck1 : 1;
	unsigned char __pt0ck2 : 1;
	unsigned char __pt0pau : 1;
} __ptm0c0_bits;

typedef union {
	__ptm0c0_bits bits;
	__sfr_byte byte;
} __ptm0c0_type;

typedef struct {
	unsigned char __pt0cclr : 1;
	unsigned char __pt0capts : 1;
	unsigned char __pt0pol : 1;
	unsigned char __pt0oc : 1;
	unsigned char __pt0io0 : 1;
	unsigned char __pt0io1 : 1;
	unsigned char __pt0m0 : 1;
	unsigned char __pt0m1 : 1;
} __ptm0c1_bits;

typedef union {
	__ptm0c1_bits bits;
	__sfr_byte byte;
} __ptm0c1_type;

typedef struct {
	unsigned char : 6;
	unsigned char __mdwov : 1;
	unsigned char __mdwef : 1;
} __mduwctrl_bits;

typedef union {
	__mduwctrl_bits bits;
	__sfr_byte byte;
} __mduwctrl_type;

typedef struct {
	unsigned char __pgas0 : 1;
	unsigned char __pgas1 : 1;
	unsigned char __pgas2 : 1;
	unsigned char __ags0 : 1;
	unsigned char __ags1 : 1;
	unsigned char __vgs0 : 1;
	unsigned char __vgs1 : 1;
	unsigned char __pgabp : 1;
} __pgac0_bits;

typedef union {
	__pgac0_bits bits;
	__sfr_byte byte;
} __pgac0_type;

typedef struct {
	unsigned char : 1;
	unsigned char __dcset0 : 1;
	unsigned char __dcset1 : 1;
	unsigned char __dcset2 : 1;
	unsigned char __inx0 : 1;
	unsigned char __inx1 : 1;
	unsigned char __inis : 1;
	unsigned char __pgabpbuf : 1;
} __pgac1_bits;

typedef union {
	__pgac1_bits bits;
	__sfr_byte byte;
} __pgac1_type;

typedef struct {
	unsigned char __chsp0 : 1;
	unsigned char __chsp1 : 1;
	unsigned char __chsp2 : 1;
	unsigned char __chsp3 : 1;
	unsigned char __chsn0 : 1;
	unsigned char __chsn1 : 1;
	unsigned char __chsn2 : 1;
	unsigned char __chsn3 : 1;
} __pgacs_bits;

typedef union {
	__pgacs_bits bits;
	__sfr_byte byte;
} __pgacs_type;

typedef struct {
	unsigned char : 2;
	unsigned char __ador0 : 1;
	unsigned char __ador1 : 1;
	unsigned char __ador2 : 1;
	unsigned char __adoff : 1;
	unsigned char __adslp : 1;
	unsigned char __adrst : 1;
} __adcr0_bits;

typedef union {
	__adcr0_bits bits;
	__sfr_byte byte;
} __adcr0_type;

typedef struct {
	unsigned char : 1;
	unsigned char __eoc : 1;
	unsigned char __adcdl : 1;
	unsigned char : 2;
	unsigned char __flms0 : 1;
	unsigned char __flms1 : 1;
	unsigned char __flms2 : 1;
} __adcr1_bits;

typedef union {
	__adcr1_bits bits;
	__sfr_byte byte;
} __adcr1_type;

typedef struct {
	unsigned char __adck0 : 1;
	unsigned char __adck1 : 1;
	unsigned char __adck2 : 1;
	unsigned char __adck3 : 1;
	unsigned char __adck4 : 1;
	unsigned char : 3;
} __adcs_bits;

typedef union {
	__adcs_bits bits;
	__sfr_byte byte;
} __adcs_type;

typedef struct {
	unsigned char __ldovs0 : 1;
	unsigned char __ldovs1 : 1;
	unsigned char __ldobps : 1;
	unsigned char : 4;
	unsigned char __ldoen : 1;
} __pwrc_bits;

typedef union {
	__pwrc_bits bits;
	__sfr_byte byte;
} __pwrc_type;

typedef struct {
	unsigned char __dacvrs0 : 1;
	unsigned char __dacvrs1 : 1;
	unsigned char : 2;
	unsigned char __irefen : 1;
	unsigned char : 1;
	unsigned char __op2do : 1;
	unsigned char __op1do : 1;
} __irefc_bits;

typedef union {
	__irefc_bits bits;
	__sfr_byte byte;
} __irefc_type;

typedef struct {
	unsigned char __opa1of0 : 1;
	unsigned char __opa1of1 : 1;
	unsigned char __opa1of2 : 1;
	unsigned char __opa1of3 : 1;
	unsigned char __opa1of4 : 1;
	unsigned char __opa1en : 1;
	unsigned char __opa1rs : 1;
	unsigned char __opa1ofm : 1;
} __opa1c_bits;

typedef union {
	__opa1c_bits bits;
	__sfr_byte byte;
} __opa1c_type;

typedef struct {
	unsigned char __opa2of0 : 1;
	unsigned char __opa2of1 : 1;
	unsigned char __opa2of2 : 1;
	unsigned char __opa2of3 : 1;
	unsigned char __opa2of4 : 1;
	unsigned char __opa2en : 1;
	unsigned char __opa2rs : 1;
	unsigned char __opa2ofm : 1;
} __opa2c_bits;

typedef union {
	__opa2c_bits bits;
	__sfr_byte byte;
} __opa2c_type;

typedef struct {
	unsigned char __gsw0 : 1;
	unsigned char __gsw1 : 1;
	unsigned char : 2;
	unsigned char __gsw4 : 1;
	unsigned char __gsw5 : 1;
	unsigned char __gsw6 : 1;
	unsigned char __gsw7 : 1;
} __gsc1_bits;

typedef union {
	__gsc1_bits bits;
	__sfr_byte byte;
} __gsc1_type;

typedef struct {
	unsigned char __gsvg00 : 1;
	unsigned char __gsvg01 : 1;
	unsigned char __gsvg02 : 1;
	unsigned char __gsvg10 : 1;
	unsigned char __gsvg11 : 1;
	unsigned char __gsvg12 : 1;
	unsigned char __gsw8 : 1;
	unsigned char __gsw9 : 1;
} __gsc2_bits;

typedef union {
	__gsc2_bits bits;
	__sfr_byte byte;
} __gsc2_type;

typedef struct {
	unsigned char __gsop1p0 : 1;
	unsigned char __gsop1p1 : 1;
	unsigned char __gsop2p0 : 1;
	unsigned char __gsop2p1 : 1;
	unsigned char : 4;
} __gsc3_bits;

typedef union {
	__gsc3_bits bits;
	__sfr_byte byte;
} __gsc3_type;

typedef struct {
	unsigned char __afeda1cm0 : 1;
	unsigned char __afeda1cm1 : 1;
	unsigned char : 6;
} __afeda1c_bits;

typedef union {
	__afeda1c_bits bits;
	__sfr_byte byte;
} __afeda1c_type;

typedef struct {
	unsigned char __afeda2cm0 : 1;
	unsigned char __afeda2cm1 : 1;
	unsigned char : 6;
} __afeda2c_bits;

typedef union {
	__afeda2c_bits bits;
	__sfr_byte byte;
} __afeda2c_type;

typedef struct {
	unsigned char __sgiqrs : 1;
	unsigned char __sgop0p0 : 1;
	unsigned char __sgop0p1 : 1;
	unsigned char : 1;
	unsigned char __bren : 1;
	unsigned char : 2;
	unsigned char __sgen : 1;
} __sgc_bits;

typedef union {
	__sgc_bits bits;
	__sfr_byte byte;
} __sgc_type;

typedef struct {
	unsigned char __op4g0 : 1;
	unsigned char __op4g1 : 1;
	unsigned char __op4g2 : 1;
	unsigned char __op4g3 : 1;
	unsigned char : 1;
	unsigned char __op3do : 1;
	unsigned char __iq_fwr : 1;
	unsigned char __bopaen : 1;
} __bopac0_bits;

typedef union {
	__bopac0_bits bits;
	__sfr_byte byte;
} __bopac0_type;

typedef struct {
	unsigned char __opa3of0 : 1;
	unsigned char __opa3of1 : 1;
	unsigned char __opa3of2 : 1;
	unsigned char __opa3of3 : 1;
	unsigned char __opa3of4 : 1;
	unsigned char __opa3en : 1;
	unsigned char __opa3rs : 1;
	unsigned char __opa3ofm : 1;
} __bopac1_bits;

typedef union {
	__bopac1_bits bits;
	__sfr_byte byte;
} __bopac1_type;

typedef struct {
	unsigned char __bsw0 : 1;
	unsigned char __bsw1 : 1;
	unsigned char __bsw2 : 1;
	unsigned char __bsw3 : 1;
	unsigned char __bsw4 : 1;
	unsigned char __bsw5 : 1;
	unsigned char __bsw6 : 1;
	unsigned char __bsw7 : 1;
} __bswc0_bits;

typedef union {
	__bswc0_bits bits;
	__sfr_byte byte;
} __bswc0_type;

typedef struct {
	unsigned char __bsw8 : 1;
	unsigned char __bsw9 : 1;
	unsigned char : 6;
} __bswc1_bits;

typedef union {
	__bswc1_bits bits;
	__sfr_byte byte;
} __bswc1_type;

typedef struct {
	unsigned char __bswsino1 : 1;
	unsigned char __bswsino2 : 1;
	unsigned char __bswsini : 1;
	unsigned char __bswrf1 : 1;
	unsigned char __bswrf2 : 1;
	unsigned char : 3;
} __bswc2_bits;

typedef union {
	__bswc2_bits bits;
	__sfr_byte byte;
} __bswc2_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt1on : 1;
	unsigned char __pt1ck0 : 1;
	unsigned char __pt1ck1 : 1;
	unsigned char __pt1ck2 : 1;
	unsigned char __pt1pau : 1;
} __ptm1c0_bits;

typedef union {
	__ptm1c0_bits bits;
	__sfr_byte byte;
} __ptm1c0_type;

typedef struct {
	unsigned char __pt1cclr : 1;
	unsigned char __pt1capts : 1;
	unsigned char __pt1pol : 1;
	unsigned char __pt1oc : 1;
	unsigned char __pt1io0 : 1;
	unsigned char __pt1io1 : 1;
	unsigned char __pt1m0 : 1;
	unsigned char __pt1m1 : 1;
} __ptm1c1_bits;

typedef union {
	__ptm1c1_bits bits;
	__sfr_byte byte;
} __ptm1c1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt2on : 1;
	unsigned char __pt2ck0 : 1;
	unsigned char __pt2ck1 : 1;
	unsigned char __pt2ck2 : 1;
	unsigned char __pt2pau : 1;
} __ptm2c0_bits;

typedef union {
	__ptm2c0_bits bits;
	__sfr_byte byte;
} __ptm2c0_type;

typedef struct {
	unsigned char __pt2cclr : 1;
	unsigned char __pt2capts : 1;
	unsigned char __pt2pol : 1;
	unsigned char __pt2oc : 1;
	unsigned char __pt2io0 : 1;
	unsigned char __pt2io1 : 1;
	unsigned char __pt2m0 : 1;
	unsigned char __pt2m1 : 1;
} __ptm2c1_bits;

typedef union {
	__ptm2c1_bits bits;
	__sfr_byte byte;
} __ptm2c1_type;

typedef struct {
	unsigned char __lcden : 1;
	unsigned char __lcdis0 : 1;
	unsigned char __lcdis1 : 1;
	unsigned char : 1;
	unsigned char __lcdp0 : 1;
	unsigned char __lcdp1 : 1;
	unsigned char __rct : 1;
	unsigned char __type : 1;
} __lcdc0_bits;

typedef union {
	__lcdc0_bits bits;
	__sfr_byte byte;
} __lcdc0_type;

typedef struct {
	unsigned char __cpvs0 : 1;
	unsigned char __cpvs1 : 1;
	unsigned char : 1;
	unsigned char __lcdpr : 1;
	unsigned char : 4;
} __lcdcp_bits;

typedef union {
	__lcdcp_bits bits;
	__sfr_byte byte;
} __lcdcp_type;

typedef struct {
	unsigned char __bias : 1;
	unsigned char __dtyc0 : 1;
	unsigned char __dtyc1 : 1;
	unsigned char : 2;
	unsigned char __lcdpck0 : 1;
	unsigned char __lcdpck1 : 1;
	unsigned char __lcdpck2 : 1;
} __lcdc2_bits;

typedef union {
	__lcdc2_bits bits;
	__sfr_byte byte;
} __lcdc2_type;

typedef struct {
	unsigned char __pd0 : 1;
	unsigned char __pd1 : 1;
	unsigned char __pd2 : 1;
	unsigned char __pd3 : 1;
	unsigned char __pd4 : 1;
	unsigned char __pd5 : 1;
	unsigned char __pd6 : 1;
	unsigned char : 1;
} __pd_bits;

typedef union {
	__pd_bits bits;
	__sfr_byte byte;
} __pd_type;

typedef struct {
	unsigned char __pdc0 : 1;
	unsigned char __pdc1 : 1;
	unsigned char __pdc2 : 1;
	unsigned char __pdc3 : 1;
	unsigned char __pdc4 : 1;
	unsigned char __pdc5 : 1;
	unsigned char __pdc6 : 1;
	unsigned char : 1;
} __pdc_bits;

typedef union {
	__pdc_bits bits;
	__sfr_byte byte;
} __pdc_type;

typedef struct {
	unsigned char __pdpu0 : 1;
	unsigned char __pdpu1 : 1;
	unsigned char __pdpu2 : 1;
	unsigned char __pdpu3 : 1;
	unsigned char __pdpu4 : 1;
	unsigned char __pdpu5 : 1;
	unsigned char __pdpu6 : 1;
	unsigned char : 1;
} __pdpu_bits;

typedef union {
	__pdpu_bits bits;
	__sfr_byte byte;
} __pdpu_type;

typedef struct {
	unsigned char __pe0 : 1;
	unsigned char __pe1 : 1;
	unsigned char __pe2 : 1;
	unsigned char __pe3 : 1;
	unsigned char __pe4 : 1;
	unsigned char __pe5 : 1;
	unsigned char __pe6 : 1;
	unsigned char __pe7 : 1;
} __pe_bits;

typedef union {
	__pe_bits bits;
	__sfr_byte byte;
} __pe_type;

typedef struct {
	unsigned char __pec0 : 1;
	unsigned char __pec1 : 1;
	unsigned char __pec2 : 1;
	unsigned char __pec3 : 1;
	unsigned char __pec4 : 1;
	unsigned char __pec5 : 1;
	unsigned char __pec6 : 1;
	unsigned char __pec7 : 1;
} __pec_bits;

typedef union {
	__pec_bits bits;
	__sfr_byte byte;
} __pec_type;

typedef struct {
	unsigned char __pepu0 : 1;
	unsigned char __pepu1 : 1;
	unsigned char __pepu2 : 1;
	unsigned char __pepu3 : 1;
	unsigned char __pepu4 : 1;
	unsigned char __pepu5 : 1;
	unsigned char __pepu6 : 1;
	unsigned char __pepu7 : 1;
} __pepu_bits;

typedef union {
	__pepu_bits bits;
	__sfr_byte byte;
} __pepu_type;

typedef struct {
	unsigned char __pf0 : 1;
	unsigned char __pf1 : 1;
	unsigned char __pf2 : 1;
	unsigned char __pf3 : 1;
	unsigned char __pf4 : 1;
	unsigned char __pf5 : 1;
	unsigned char __pf6 : 1;
	unsigned char __pf7 : 1;
} __pf_bits;

typedef union {
	__pf_bits bits;
	__sfr_byte byte;
} __pf_type;

typedef struct {
	unsigned char __pfc0 : 1;
	unsigned char __pfc1 : 1;
	unsigned char __pfc2 : 1;
	unsigned char __pfc3 : 1;
	unsigned char __pfc4 : 1;
	unsigned char __pfc5 : 1;
	unsigned char __pfc6 : 1;
	unsigned char __pfc7 : 1;
} __pfc_bits;

typedef union {
	__pfc_bits bits;
	__sfr_byte byte;
} __pfc_type;

typedef struct {
	unsigned char __pfpu0 : 1;
	unsigned char __pfpu1 : 1;
	unsigned char __pfpu2 : 1;
	unsigned char __pfpu3 : 1;
	unsigned char __pfpu4 : 1;
	unsigned char __pfpu5 : 1;
	unsigned char __pfpu6 : 1;
	unsigned char __pfpu7 : 1;
} __pfpu_bits;

typedef union {
	__pfpu_bits bits;
	__sfr_byte byte;
} __pfpu_type;

typedef struct {
	unsigned char __pg0 : 1;
	unsigned char __pg1 : 1;
	unsigned char __pg2 : 1;
	unsigned char : 5;
} __pg_bits;

typedef union {
	__pg_bits bits;
	__sfr_byte byte;
} __pg_type;

typedef struct {
	unsigned char __pgc0 : 1;
	unsigned char __pgc1 : 1;
	unsigned char __pgc2 : 1;
	unsigned char : 5;
} __pgc_bits;

typedef union {
	__pgc_bits bits;
	__sfr_byte byte;
} __pgc_type;

typedef struct {
	unsigned char __pgpu0 : 1;
	unsigned char __pgpu1 : 1;
	unsigned char __pgpu2 : 1;
	unsigned char : 5;
} __pgpu_bits;

typedef union {
	__pgpu_bits bits;
	__sfr_byte byte;
} __pgpu_type;

typedef struct {
	unsigned char __rd : 1;
	unsigned char __rden : 1;
	unsigned char __wr : 1;
	unsigned char __wren : 1;
	unsigned char : 4;
} __eec_bits;

typedef union {
	__eec_bits bits;
	__sfr_byte byte;
} __eec_type;

typedef struct {
	unsigned char __frd : 1;
	unsigned char __frden : 1;
	unsigned char __fwt : 1;
	unsigned char __fwpen : 1;
	unsigned char __fmod0 : 1;
	unsigned char __fmod1 : 1;
	unsigned char __fmod2 : 1;
	unsigned char __cfwen : 1;
} __fc0_bits;

typedef union {
	__fc0_bits bits;
	__sfr_byte byte;
} __fc0_type;

typedef struct {
	unsigned char __clwb : 1;
	unsigned char : 7;
} __fc2_bits;

typedef union {
	__fc2_bits bits;
	__sfr_byte byte;
} __fc2_type;

typedef struct {
	unsigned char __fa0 : 1;
	unsigned char __fa1 : 1;
	unsigned char __fa2 : 1;
	unsigned char __fa3 : 1;
	unsigned char __fa4 : 1;
	unsigned char __fa5 : 1;
	unsigned char __fa6 : 1;
	unsigned char __fa7 : 1;
} __farl_bits;

typedef union {
	__farl_bits bits;
	__sfr_byte byte;
} __farl_type;

typedef struct {
	unsigned char __fa8 : 1;
	unsigned char __fa9 : 1;
	unsigned char __fa10 : 1;
	unsigned char __fa11 : 1;
	unsigned char __fa12 : 1;
	unsigned char __fa13 : 1;
	unsigned char __fa14 : 1;
	unsigned char __fa15 : 1;
} __farh_bits;

typedef union {
	__farh_bits bits;
	__sfr_byte byte;
} __farh_type;

typedef struct {
	unsigned char __stckps : 1;
	unsigned char : 2;
	unsigned char __ptck2ps : 1;
	unsigned char : 1;
	unsigned char __ptp0ips : 1;
	unsigned char __ptp1ips : 1;
	unsigned char __ptp2ips : 1;
} __ifs0_bits;

typedef union {
	__ifs0_bits bits;
	__sfr_byte byte;
} __ifs0_type;

typedef struct {
	unsigned char : 4;
	unsigned char __spisckps : 1;
	unsigned char __spisdips : 1;
	unsigned char __spiscsbps : 1;
	unsigned char : 1;
} __ifs1_bits;

typedef union {
	__ifs1_bits bits;
	__sfr_byte byte;
} __ifs1_type;

typedef struct {
	unsigned char __pas00 : 1;
	unsigned char __pas01 : 1;
	unsigned char __pas02 : 1;
	unsigned char __pas03 : 1;
	unsigned char __pas04 : 1;
	unsigned char __pas05 : 1;
	unsigned char __pas06 : 1;
	unsigned char __pas07 : 1;
} __pas0_bits;

typedef union {
	__pas0_bits bits;
	__sfr_byte byte;
} __pas0_type;

typedef struct {
	unsigned char __pas10 : 1;
	unsigned char __pas11 : 1;
	unsigned char __pas12 : 1;
	unsigned char __pas13 : 1;
	unsigned char __pas14 : 1;
	unsigned char __pas15 : 1;
	unsigned char __pas16 : 1;
	unsigned char __pas17 : 1;
} __pas1_bits;

typedef union {
	__pas1_bits bits;
	__sfr_byte byte;
} __pas1_type;

typedef struct {
	unsigned char __pbs00 : 1;
	unsigned char __pbs01 : 1;
	unsigned char __pbs02 : 1;
	unsigned char __pbs03 : 1;
	unsigned char __pbs04 : 1;
	unsigned char __pbs05 : 1;
	unsigned char __pbs06 : 1;
	unsigned char __pbs07 : 1;
} __pbs0_bits;

typedef union {
	__pbs0_bits bits;
	__sfr_byte byte;
} __pbs0_type;

typedef struct {
	unsigned char __pcs00 : 1;
	unsigned char __pcs01 : 1;
	unsigned char __pcs02 : 1;
	unsigned char __pcs03 : 1;
	unsigned char __pcs04 : 1;
	unsigned char __pcs05 : 1;
	unsigned char __pcs06 : 1;
	unsigned char __pcs07 : 1;
} __pcs0_bits;

typedef union {
	__pcs0_bits bits;
	__sfr_byte byte;
} __pcs0_type;

typedef struct {
	unsigned char __pcs10 : 1;
	unsigned char __pcs11 : 1;
	unsigned char __pcs12 : 1;
	unsigned char __pcs13 : 1;
	unsigned char : 4;
} __pcs1_bits;

typedef union {
	__pcs1_bits bits;
	__sfr_byte byte;
} __pcs1_type;

typedef struct {
	unsigned char __pds00 : 1;
	unsigned char __pds01 : 1;
	unsigned char __pds02 : 1;
	unsigned char __pds03 : 1;
	unsigned char __pds04 : 1;
	unsigned char __pds05 : 1;
	unsigned char __pds06 : 1;
	unsigned char __pds07 : 1;
} __pds0_bits;

typedef union {
	__pds0_bits bits;
	__sfr_byte byte;
} __pds0_type;

typedef struct {
	unsigned char __pds10 : 1;
	unsigned char __pds11 : 1;
	unsigned char __pds12 : 1;
	unsigned char __pds13 : 1;
	unsigned char __pds14 : 1;
	unsigned char __pds15 : 1;
	unsigned char : 2;
} __pds1_bits;

typedef union {
	__pds1_bits bits;
	__sfr_byte byte;
} __pds1_type;

typedef struct {
	unsigned char __pes00 : 1;
	unsigned char __pes01 : 1;
	unsigned char __pes02 : 1;
	unsigned char __pes03 : 1;
	unsigned char __pes04 : 1;
	unsigned char __pes05 : 1;
	unsigned char __pes06 : 1;
	unsigned char __pes07 : 1;
} __pes0_bits;

typedef union {
	__pes0_bits bits;
	__sfr_byte byte;
} __pes0_type;

typedef struct {
	unsigned char __pes10 : 1;
	unsigned char __pes11 : 1;
	unsigned char __pes12 : 1;
	unsigned char __pes13 : 1;
	unsigned char __pes14 : 1;
	unsigned char __pes15 : 1;
	unsigned char __pes16 : 1;
	unsigned char __pes17 : 1;
} __pes1_bits;

typedef union {
	__pes1_bits bits;
	__sfr_byte byte;
} __pes1_type;

typedef struct {
	unsigned char __pfs00 : 1;
	unsigned char __pfs01 : 1;
	unsigned char __pfs02 : 1;
	unsigned char __pfs03 : 1;
	unsigned char __pfs04 : 1;
	unsigned char __pfs05 : 1;
	unsigned char __pfs06 : 1;
	unsigned char __pfs07 : 1;
} __pfs0_bits;

typedef union {
	__pfs0_bits bits;
	__sfr_byte byte;
} __pfs0_type;

typedef struct {
	unsigned char __pfs10 : 1;
	unsigned char __pfs11 : 1;
	unsigned char __pfs12 : 1;
	unsigned char __pfs13 : 1;
	unsigned char __pfs14 : 1;
	unsigned char __pfs15 : 1;
	unsigned char __pfs16 : 1;
	unsigned char __pfs17 : 1;
} __pfs1_bits;

typedef union {
	__pfs1_bits bits;
	__sfr_byte byte;
} __pfs1_type;

typedef struct {
	unsigned char __pgs00 : 1;
	unsigned char __pgs01 : 1;
	unsigned char __pgs02 : 1;
	unsigned char __pgs03 : 1;
	unsigned char __pgs04 : 1;
	unsigned char __pgs05 : 1;
	unsigned char : 2;
} __pgs0_bits;

typedef union {
	__pgs0_bits bits;
	__sfr_byte byte;
} __pgs0_type;

typedef struct {
	unsigned char __sledc00 : 1;
	unsigned char __sledc01 : 1;
	unsigned char __sledc02 : 1;
	unsigned char __sledc03 : 1;
	unsigned char __sledc04 : 1;
	unsigned char __sledc05 : 1;
	unsigned char : 2;
} __sledc0_bits;

typedef union {
	__sledc0_bits bits;
	__sfr_byte byte;
} __sledc0_type;

typedef struct {
	unsigned char __sledc10 : 1;
	unsigned char __sledc11 : 1;
	unsigned char __sledc12 : 1;
	unsigned char __sledc13 : 1;
	unsigned char __sledc14 : 1;
	unsigned char __sledc15 : 1;
	unsigned char __sledc16 : 1;
	unsigned char __sledc17 : 1;
} __sledc1_bits;

typedef union {
	__sledc1_bits bits;
	__sfr_byte byte;
} __sledc1_type;

typedef struct {
	unsigned char __sledc20 : 1;
	unsigned char __sledc21 : 1;
	unsigned char __sledc22 : 1;
	unsigned char __sledc23 : 1;
	unsigned char __sledc24 : 1;
	unsigned char __sledc25 : 1;
	unsigned char __sledc26 : 1;
	unsigned char __sledc27 : 1;
} __sledc2_bits;

typedef union {
	__sledc2_bits bits;
	__sfr_byte byte;
} __sledc2_type;

typedef struct {
	unsigned char __sledc30 : 1;
	unsigned char __sledc31 : 1;
	unsigned char : 6;
} __sledc3_bits;

typedef union {
	__sledc3_bits bits;
	__sfr_byte byte;
} __sledc3_type;


DEFINE_SFR(__sfr_byte, __mp0, 0x01);
DEFINE_SFR(__sfr_byte, __mp1l, 0x03);
DEFINE_SFR(__sfr_byte, __mp1h, 0x04);
DEFINE_SFR(__sfr_byte, __acc, 0x05);
DEFINE_SFR(__sfr_byte, __pcl, 0x06);
DEFINE_SFR(__sfr_byte, __tblp, 0x07);
DEFINE_SFR(__sfr_byte, __tblh, 0x08);
DEFINE_SFR(__sfr_byte, __tbhp, 0x09);
DEFINE_SFR(__status_type, __status, 0x0a);
DEFINE_SFR(__pbp_type, __pbp, 0x0b);
DEFINE_SFR(__sfr_byte, __mp2l, 0x0d);
DEFINE_SFR(__sfr_byte, __mp2h, 0x0e);
DEFINE_SFR(__rstfc_type, __rstfc, 0x0f);
DEFINE_SFR(__scc_type, __scc, 0x10);
DEFINE_SFR(__hircc_type, __hircc, 0x11);
DEFINE_SFR(__hxtc_type, __hxtc, 0x12);
DEFINE_SFR(__lxtc_type, __lxtc, 0x13);
DEFINE_SFR(__pa_type, __pa, 0x14);
DEFINE_SFR(__pac_type, __pac, 0x15);
DEFINE_SFR(__papu_type, __papu, 0x16);
DEFINE_SFR(__pawu_type, __pawu, 0x17);
DEFINE_SFR(__rstc_type, __rstc, 0x18);
DEFINE_SFR(__lvrc_type, __lvrc, 0x19);
DEFINE_SFR(__lvdc_type, __lvdc, 0x1a);
DEFINE_SFR(__mfi0_type, __mfi0, 0x1b);
DEFINE_SFR(__mfi1_type, __mfi1, 0x1c);
DEFINE_SFR(__mfi2_type, __mfi2, 0x1d);
DEFINE_SFR(__wdtc_type, __wdtc, 0x1e);
DEFINE_SFR(__integ0_type, __integ0, 0x1f);
DEFINE_SFR(__intc0_type, __intc0, 0x20);
DEFINE_SFR(__intc1_type, __intc1, 0x21);
DEFINE_SFR(__intc2_type, __intc2, 0x22);
DEFINE_SFR(__intc3_type, __intc3, 0x23);
DEFINE_SFR(__pb_type, __pb, 0x24);
DEFINE_SFR(__pbc_type, __pbc, 0x25);
DEFINE_SFR(__pbpu_type, __pbpu, 0x26);
DEFINE_SFR(__pc_type, __pc, 0x27);
DEFINE_SFR(__pcc_type, __pcc, 0x28);
DEFINE_SFR(__pcpu_type, __pcpu, 0x29);
DEFINE_SFR(__integ1_type, __integ1, 0x2b);
DEFINE_SFR(__pscr_type, __pscr, 0x2c);
DEFINE_SFR(__tb0c_type, __tb0c, 0x2d);
DEFINE_SFR(__tb1c_type, __tb1c, 0x2e);
DEFINE_SFR(__u0sr_type, __u0sr, 0x2f);
DEFINE_SFR(__u0cr1_type, __u0cr1, 0x30);
DEFINE_SFR(__u0cr2_type, __u0cr2, 0x31);
DEFINE_SFR(__txr_rxr0_type, __txr_rxr0, 0x32);
DEFINE_SFR(__brg0_type, __brg0, 0x33);
DEFINE_SFR(__simc0_type, __simc0, 0x34);
DEFINE_SFR(__simc1_type, __simc1, 0x35);
DEFINE_SFR(__sfr_byte, __simd, 0x36);
DEFINE_SFR(__sima_type, __sima, 0x37);
DEFINE_SFR(__simc2_type, __simc2, 0x37);
DEFINE_SFR(__simtoc_type, __simtoc, 0x38);
DEFINE_SFR(__spic0_type, __spic0, 0x3a);
DEFINE_SFR(__spic1_type, __spic1, 0x3b);
DEFINE_SFR(__sfr_byte, __spid, 0x3c);
DEFINE_SFR(__ovpc0_type, __ovpc0, 0x3d);
DEFINE_SFR(__ovpc1_type, __ovpc1, 0x3e);
DEFINE_SFR(__sfr_byte, __ovpda, 0x3f);
DEFINE_SFR(__eea_type, __eea, 0x41);
DEFINE_SFR(__sfr_byte, __eed, 0x42);
DEFINE_SFR(__u1sr_type, __u1sr, 0x44);
DEFINE_SFR(__u1cr1_type, __u1cr1, 0x45);
DEFINE_SFR(__u1cr2_type, __u1cr2, 0x46);
DEFINE_SFR(__txr_rxr1_type, __txr_rxr1, 0x47);
DEFINE_SFR(__brg1_type, __brg1, 0x48);
DEFINE_SFR(__stmc0_type, __stmc0, 0x49);
DEFINE_SFR(__stmc1_type, __stmc1, 0x4a);
DEFINE_SFR(__sfr_byte, __stmdl, 0x4b);
DEFINE_SFR(__sfr_byte, __stmdh, 0x4c);
DEFINE_SFR(__sfr_byte, __stmal, 0x4d);
DEFINE_SFR(__sfr_byte, __stmah, 0x4e);
DEFINE_SFR(__sfr_byte, __stmrp, 0x4f);
DEFINE_SFR(__ptm0c0_type, __ptm0c0, 0x50);
DEFINE_SFR(__ptm0c1_type, __ptm0c1, 0x51);
DEFINE_SFR(__sfr_byte, __ptm0dl, 0x52);
DEFINE_SFR(__sfr_byte, __ptm0dh, 0x53);
DEFINE_SFR(__sfr_byte, __ptm0al, 0x54);
DEFINE_SFR(__sfr_byte, __ptm0ah, 0x55);
DEFINE_SFR(__sfr_byte, __ptm0rpl, 0x56);
DEFINE_SFR(__sfr_byte, __ptm0rph, 0x57);
DEFINE_SFR(__sfr_byte, __mduwr0, 0x59);
DEFINE_SFR(__sfr_byte, __mduwr1, 0x5a);
DEFINE_SFR(__sfr_byte, __mduwr2, 0x5b);
DEFINE_SFR(__sfr_byte, __mduwr3, 0x5c);
DEFINE_SFR(__sfr_byte, __mduwr4, 0x5d);
DEFINE_SFR(__sfr_byte, __mduwr5, 0x5e);
DEFINE_SFR(__mduwctrl_type, __mduwctrl, 0x5f);
DEFINE_SFR(__pgac0_type, __pgac0, 0x60);
DEFINE_SFR(__pgac1_type, __pgac1, 0x61);
DEFINE_SFR(__pgacs_type, __pgacs, 0x62);
DEFINE_SFR(__sfr_byte, __adrl, 0x63);
DEFINE_SFR(__sfr_byte, __adrm, 0x64);
DEFINE_SFR(__sfr_byte, __adrh, 0x65);
DEFINE_SFR(__adcr0_type, __adcr0, 0x66);
DEFINE_SFR(__adcr1_type, __adcr1, 0x67);
DEFINE_SFR(__adcs_type, __adcs, 0x68);
DEFINE_SFR(__pwrc_type, __pwrc, 0x6a);
DEFINE_SFR(__irefc_type, __irefc, 0x6b);
DEFINE_SFR(__sfr_byte, __pvref, 0x6c);
DEFINE_SFR(__opa1c_type, __opa1c, 0x6d);
DEFINE_SFR(__opa2c_type, __opa2c, 0x6e);
DEFINE_SFR(__gsc1_type, __gsc1, 0x6f);
DEFINE_SFR(__gsc2_type, __gsc2, 0x70);
DEFINE_SFR(__gsc3_type, __gsc3, 0x71);
DEFINE_SFR(__afeda1c_type, __afeda1c, 0x72);
DEFINE_SFR(__sfr_byte, __afeda1l, 0x73);
DEFINE_SFR(__sfr_byte, __afeda1h, 0x74);
DEFINE_SFR(__afeda2c_type, __afeda2c, 0x75);
DEFINE_SFR(__sfr_byte, __afeda2l, 0x76);
DEFINE_SFR(__sfr_byte, __afeda2h, 0x77);
DEFINE_SFR(__sgc_type, __sgc, 0x78);
DEFINE_SFR(__sfr_byte, __sgn, 0x79);
DEFINE_SFR(__sfr_byte, __sgdnr, 0x7a);
DEFINE_SFR(__bopac0_type, __bopac0, 0x7b);
DEFINE_SFR(__bopac1_type, __bopac1, 0x7c);
DEFINE_SFR(__bswc0_type, __bswc0, 0x7d);
DEFINE_SFR(__bswc1_type, __bswc1, 0x7e);
DEFINE_SFR(__bswc2_type, __bswc2, 0x7f);
DEFINE_SFR(__ptm1c0_type, __ptm1c0, 0x120);
DEFINE_SFR(__ptm1c1_type, __ptm1c1, 0x121);
DEFINE_SFR(__sfr_byte, __ptm1dl, 0x122);
DEFINE_SFR(__sfr_byte, __ptm1dh, 0x123);
DEFINE_SFR(__sfr_byte, __ptm1al, 0x124);
DEFINE_SFR(__sfr_byte, __ptm1ah, 0x125);
DEFINE_SFR(__sfr_byte, __ptm1rpl, 0x126);
DEFINE_SFR(__sfr_byte, __ptm1rph, 0x127);
DEFINE_SFR(__ptm2c0_type, __ptm2c0, 0x128);
DEFINE_SFR(__ptm2c1_type, __ptm2c1, 0x129);
DEFINE_SFR(__sfr_byte, __ptm2dl, 0x12a);
DEFINE_SFR(__sfr_byte, __ptm2dh, 0x12b);
DEFINE_SFR(__sfr_byte, __ptm2al, 0x12c);
DEFINE_SFR(__sfr_byte, __ptm2ah, 0x12d);
DEFINE_SFR(__sfr_byte, __ptm2rpl, 0x12e);
DEFINE_SFR(__sfr_byte, __ptm2rph, 0x12f);
DEFINE_SFR(__lcdc0_type, __lcdc0, 0x130);
DEFINE_SFR(__lcdcp_type, __lcdcp, 0x131);
DEFINE_SFR(__lcdc2_type, __lcdc2, 0x132);
DEFINE_SFR(__pd_type, __pd, 0x134);
DEFINE_SFR(__pdc_type, __pdc, 0x135);
DEFINE_SFR(__pdpu_type, __pdpu, 0x136);
DEFINE_SFR(__pe_type, __pe, 0x137);
DEFINE_SFR(__pec_type, __pec, 0x138);
DEFINE_SFR(__pepu_type, __pepu, 0x139);
DEFINE_SFR(__pf_type, __pf, 0x13a);
DEFINE_SFR(__pfc_type, __pfc, 0x13b);
DEFINE_SFR(__pfpu_type, __pfpu, 0x13c);
DEFINE_SFR(__pg_type, __pg, 0x13d);
DEFINE_SFR(__pgc_type, __pgc, 0x13e);
DEFINE_SFR(__pgpu_type, __pgpu, 0x13f);
DEFINE_SFR(__eec_type, __eec, 0x140);
DEFINE_SFR(__fc0_type, __fc0, 0x143);
DEFINE_SFR(__sfr_byte, __fc1, 0x144);
DEFINE_SFR(__fc2_type, __fc2, 0x145);
DEFINE_SFR(__farl_type, __farl, 0x146);
DEFINE_SFR(__farh_type, __farh, 0x147);
DEFINE_SFR(__sfr_byte, __fd0l, 0x148);
DEFINE_SFR(__sfr_byte, __fd0h, 0x149);
DEFINE_SFR(__sfr_byte, __fd1l, 0x14a);
DEFINE_SFR(__sfr_byte, __fd1h, 0x14b);
DEFINE_SFR(__sfr_byte, __fd2l, 0x14c);
DEFINE_SFR(__sfr_byte, __fd2h, 0x14d);
DEFINE_SFR(__sfr_byte, __fd3l, 0x14e);
DEFINE_SFR(__sfr_byte, __fd3h, 0x14f);
DEFINE_SFR(__ifs0_type, __ifs0, 0x150);
DEFINE_SFR(__ifs1_type, __ifs1, 0x151);
DEFINE_SFR(__pas0_type, __pas0, 0x153);
DEFINE_SFR(__pas1_type, __pas1, 0x154);
DEFINE_SFR(__pbs0_type, __pbs0, 0x155);
DEFINE_SFR(__pcs0_type, __pcs0, 0x157);
DEFINE_SFR(__pcs1_type, __pcs1, 0x158);
DEFINE_SFR(__pds0_type, __pds0, 0x159);
DEFINE_SFR(__pds1_type, __pds1, 0x15a);
DEFINE_SFR(__pes0_type, __pes0, 0x15b);
DEFINE_SFR(__pes1_type, __pes1, 0x15c);
DEFINE_SFR(__pfs0_type, __pfs0, 0x15d);
DEFINE_SFR(__pfs1_type, __pfs1, 0x15e);
DEFINE_SFR(__pgs0_type, __pgs0, 0x15f);
DEFINE_SFR(__sledc0_type, __sledc0, 0x160);
DEFINE_SFR(__sledc1_type, __sledc1, 0x161);
DEFINE_SFR(__sledc2_type, __sledc2, 0x162);
DEFINE_SFR(__sledc3_type, __sledc3, 0x163);
DEFINE_SFR(__sfr_byte, __iar0, 0x00);
DEFINE_SFR(__sfr_byte, __iar1, 0x02);
DEFINE_SFR(__sfr_byte, __iar2, 0x0C);

#define _iar0     __iar0
#define _iar1     __iar1
#define _iar2     __iar2
#define _mp0      __mp0
#define _mp1l     __mp1l
#define _mp1h     __mp1h
#define _acc      __acc
#define _pcl      __pcl
#define _tblp     __tblp
#define _tblh     __tblh
#define _tbhp     __tbhp
#define _status   __status.byte
#define _pbp      __pbp.byte
#define _mp2l     __mp2l
#define _mp2h     __mp2h
#define _rstfc    __rstfc.byte
#define _scc      __scc.byte
#define _hircc    __hircc.byte
#define _hxtc     __hxtc.byte
#define _lxtc     __lxtc.byte
#define _pa       __pa.byte
#define _pac      __pac.byte
#define _papu     __papu.byte
#define _pawu     __pawu.byte
#define _rstc     __rstc.byte
#define _lvrc     __lvrc.byte
#define _lvdc     __lvdc.byte
#define _mfi0     __mfi0.byte
#define _mfi1     __mfi1.byte
#define _mfi2     __mfi2.byte
#define _wdtc     __wdtc.byte
#define _integ0   __integ0.byte
#define _intc0    __intc0.byte
#define _intc1    __intc1.byte
#define _intc2    __intc2.byte
#define _intc3    __intc3.byte
#define _pb       __pb.byte
#define _pbc      __pbc.byte
#define _pbpu     __pbpu.byte
#define _pc       __pc.byte
#define _pcc      __pcc.byte
#define _pcpu     __pcpu.byte
#define _integ1   __integ1.byte
#define _pscr     __pscr.byte
#define _tb0c     __tb0c.byte
#define _tb1c     __tb1c.byte
#define _u0sr     __u0sr.byte
#define _u0cr1    __u0cr1.byte
#define _u0cr2    __u0cr2.byte
#define _txr_rxr0 __txr_rxr0.byte
#define _brg0     __brg0.byte
#define _simc0    __simc0.byte
#define _simc1    __simc1.byte
#define _simd     __simd
#define _sima     __sima.byte
#define _simc2    __simc2.byte
#define _simtoc   __simtoc.byte
#define _spic0    __spic0.byte
#define _spic1    __spic1.byte
#define _spid     __spid
#define _ovpc0    __ovpc0.byte
#define _ovpc1    __ovpc1.byte
#define _ovpda    __ovpda
#define _eea      __eea.byte
#define _eed      __eed
#define _u1sr     __u1sr.byte
#define _u1cr1    __u1cr1.byte
#define _u1cr2    __u1cr2.byte
#define _txr_rxr1 __txr_rxr1.byte
#define _brg1     __brg1.byte
#define _stmc0    __stmc0.byte
#define _stmc1    __stmc1.byte
#define _stmdl    __stmdl
#define _stmdh    __stmdh
#define _stmal    __stmal
#define _stmah    __stmah
#define _stmrp    __stmrp
#define _ptm0c0   __ptm0c0.byte
#define _ptm0c1   __ptm0c1.byte
#define _ptm0dl   __ptm0dl
#define _ptm0dh   __ptm0dh
#define _ptm0al   __ptm0al
#define _ptm0ah   __ptm0ah
#define _ptm0rpl  __ptm0rpl
#define _ptm0rph  __ptm0rph
#define _mduwr0   __mduwr0
#define _mduwr1   __mduwr1
#define _mduwr2   __mduwr2
#define _mduwr3   __mduwr3
#define _mduwr4   __mduwr4
#define _mduwr5   __mduwr5
#define _mduwctrl __mduwctrl.byte
#define _pgac0    __pgac0.byte
#define _pgac1    __pgac1.byte
#define _pgacs    __pgacs.byte
#define _adrl     __adrl
#define _adrm     __adrm
#define _adrh     __adrh
#define _adcr0    __adcr0.byte
#define _adcr1    __adcr1.byte
#define _adcs     __adcs.byte
#define _pwrc     __pwrc.byte
#define _irefc    __irefc.byte
#define _pvref    __pvref
#define _opa1c    __opa1c.byte
#define _opa2c    __opa2c.byte
#define _gsc1     __gsc1.byte
#define _gsc2     __gsc2.byte
#define _gsc3     __gsc3.byte
#define _afeda1c  __afeda1c.byte
#define _afeda1l  __afeda1l
#define _afeda1h  __afeda1h
#define _afeda2c  __afeda2c.byte
#define _afeda2l  __afeda2l
#define _afeda2h  __afeda2h
#define _sgc      __sgc.byte
#define _sgn      __sgn
#define _sgdnr    __sgdnr
#define _bopac0   __bopac0.byte
#define _bopac1   __bopac1.byte
#define _bswc0    __bswc0.byte
#define _bswc1    __bswc1.byte
#define _bswc2    __bswc2.byte
#define _ptm1c0   __ptm1c0.byte
#define _ptm1c1   __ptm1c1.byte
#define _ptm1dl   __ptm1dl
#define _ptm1dh   __ptm1dh
#define _ptm1al   __ptm1al
#define _ptm1ah   __ptm1ah
#define _ptm1rpl  __ptm1rpl
#define _ptm1rph  __ptm1rph
#define _ptm2c0   __ptm2c0.byte
#define _ptm2c1   __ptm2c1.byte
#define _ptm2dl   __ptm2dl
#define _ptm2dh   __ptm2dh
#define _ptm2al   __ptm2al
#define _ptm2ah   __ptm2ah
#define _ptm2rpl  __ptm2rpl
#define _ptm2rph  __ptm2rph
#define _lcdc0    __lcdc0.byte
#define _lcdcp    __lcdcp.byte
#define _lcdc2    __lcdc2.byte
#define _pd       __pd.byte
#define _pdc      __pdc.byte
#define _pdpu     __pdpu.byte
#define _pe       __pe.byte
#define _pec      __pec.byte
#define _pepu     __pepu.byte
#define _pf       __pf.byte
#define _pfc      __pfc.byte
#define _pfpu     __pfpu.byte
#define _pg       __pg.byte
#define _pgc      __pgc.byte
#define _pgpu     __pgpu.byte
#define _eec      __eec.byte
#define _fc0      __fc0.byte
#define _fc1      __fc1
#define _fc2      __fc2.byte
#define _farl     __farl.byte
#define _farh     __farh.byte
#define _fd0l     __fd0l
#define _fd0h     __fd0h
#define _fd1l     __fd1l
#define _fd1h     __fd1h
#define _fd2l     __fd2l
#define _fd2h     __fd2h
#define _fd3l     __fd3l
#define _fd3h     __fd3h
#define _ifs0     __ifs0.byte
#define _ifs1     __ifs1.byte
#define _pas0     __pas0.byte
#define _pas1     __pas1.byte
#define _pbs0     __pbs0.byte
#define _pcs0     __pcs0.byte
#define _pcs1     __pcs1.byte
#define _pds0     __pds0.byte
#define _pds1     __pds1.byte
#define _pes0     __pes0.byte
#define _pes1     __pes1.byte
#define _pfs0     __pfs0.byte
#define _pfs1     __pfs1.byte
#define _pgs0     __pgs0.byte
#define _sledc0   __sledc0.byte
#define _sledc1   __sledc1.byte
#define _sledc2   __sledc2.byte
#define _sledc3   __sledc3.byte

#define _c        __status.bits.__c
#define _ac       __status.bits.__ac
#define _z        __status.bits.__z
#define _ov       __status.bits.__ov
#define _pdf      __status.bits.__pdf
#define _to       __status.bits.__to
#define _cz       __status.bits.__cz
#define _sc       __status.bits.__sc
#define _pbp0     __pbp.bits.__pbp0
#define _pbp1     __pbp.bits.__pbp1
#define _pbp2     __pbp.bits.__pbp2
#define _wrf      __rstfc.bits.__wrf
#define _lrf      __rstfc.bits.__lrf
#define _lvrf     __rstfc.bits.__lvrf
#define _rstf     __rstfc.bits.__rstf
#define _fsiden   __scc.bits.__fsiden
#define _fhiden   __scc.bits.__fhiden
#define _fss      __scc.bits.__fss
#define _fhs      __scc.bits.__fhs
#define _cks0     __scc.bits.__cks0
#define _cks1     __scc.bits.__cks1
#define _cks2     __scc.bits.__cks2
#define _hircen   __hircc.bits.__hircen
#define _hircf    __hircc.bits.__hircf
#define _hirc0    __hircc.bits.__hirc0
#define _hirc1    __hircc.bits.__hirc1
#define _hxten    __hxtc.bits.__hxten
#define _hxtf     __hxtc.bits.__hxtf
#define _hxtm     __hxtc.bits.__hxtm
#define _lxten    __lxtc.bits.__lxten
#define _lxtf     __lxtc.bits.__lxtf
#define _pa0      __pa.bits.__pa0
#define _pa1      __pa.bits.__pa1
#define _pa2      __pa.bits.__pa2
#define _pa3      __pa.bits.__pa3
#define _pa4      __pa.bits.__pa4
#define _pa5      __pa.bits.__pa5
#define _pa6      __pa.bits.__pa6
#define _pa7      __pa.bits.__pa7
#define _pac0     __pac.bits.__pac0
#define _pac1     __pac.bits.__pac1
#define _pac2     __pac.bits.__pac2
#define _pac3     __pac.bits.__pac3
#define _pac4     __pac.bits.__pac4
#define _pac5     __pac.bits.__pac5
#define _pac6     __pac.bits.__pac6
#define _pac7     __pac.bits.__pac7
#define _papu0    __papu.bits.__papu0
#define _papu1    __papu.bits.__papu1
#define _papu2    __papu.bits.__papu2
#define _papu3    __papu.bits.__papu3
#define _papu4    __papu.bits.__papu4
#define _papu5    __papu.bits.__papu5
#define _papu6    __papu.bits.__papu6
#define _papu7    __papu.bits.__papu7
#define _pawu0    __pawu.bits.__pawu0
#define _pawu1    __pawu.bits.__pawu1
#define _pawu2    __pawu.bits.__pawu2
#define _pawu3    __pawu.bits.__pawu3
#define _pawu4    __pawu.bits.__pawu4
#define _pawu5    __pawu.bits.__pawu5
#define _pawu6    __pawu.bits.__pawu6
#define _pawu7    __pawu.bits.__pawu7
#define _rstc0    __rstc.bits.__rstc0
#define _rstc1    __rstc.bits.__rstc1
#define _rstc2    __rstc.bits.__rstc2
#define _rstc3    __rstc.bits.__rstc3
#define _rstc4    __rstc.bits.__rstc4
#define _rstc5    __rstc.bits.__rstc5
#define _rstc6    __rstc.bits.__rstc6
#define _rstc7    __rstc.bits.__rstc7
#define _lvs0     __lvrc.bits.__lvs0
#define _lvs1     __lvrc.bits.__lvs1
#define _lvs2     __lvrc.bits.__lvs2
#define _lvs3     __lvrc.bits.__lvs3
#define _lvs4     __lvrc.bits.__lvs4
#define _lvs5     __lvrc.bits.__lvs5
#define _lvs6     __lvrc.bits.__lvs6
#define _lvs7     __lvrc.bits.__lvs7
#define _vlvd0    __lvdc.bits.__vlvd0
#define _vlvd1    __lvdc.bits.__vlvd1
#define _vlvd2    __lvdc.bits.__vlvd2
#define _vbgen    __lvdc.bits.__vbgen
#define _lvden    __lvdc.bits.__lvden
#define _lvdo     __lvdc.bits.__lvdo
#define _stmpe    __mfi0.bits.__stmpe
#define _stmae    __mfi0.bits.__stmae
#define _ptm0pe   __mfi0.bits.__ptm0pe
#define _ptm0ae   __mfi0.bits.__ptm0ae
#define _stmpf    __mfi0.bits.__stmpf
#define _stmaf    __mfi0.bits.__stmaf
#define _ptm0pf   __mfi0.bits.__ptm0pf
#define _ptm0af   __mfi0.bits.__ptm0af
#define _ptm1pe   __mfi1.bits.__ptm1pe
#define _ptm1ae   __mfi1.bits.__ptm1ae
#define _ptm2pe   __mfi1.bits.__ptm2pe
#define _ptm2ae   __mfi1.bits.__ptm2ae
#define _ptm1pf   __mfi1.bits.__ptm1pf
#define _ptm1af   __mfi1.bits.__ptm1af
#define _ptm2pf   __mfi1.bits.__ptm2pf
#define _ptm2af   __mfi1.bits.__ptm2af
#define _lve      __mfi2.bits.__lve
#define _dee      __mfi2.bits.__dee
#define _int4e    __mfi2.bits.__int4e
#define _int5e    __mfi2.bits.__int5e
#define _lvf      __mfi2.bits.__lvf
#define _def      __mfi2.bits.__def
#define _int4f    __mfi2.bits.__int4f
#define _int5f    __mfi2.bits.__int5f
#define _ws0      __wdtc.bits.__ws0
#define _ws1      __wdtc.bits.__ws1
#define _ws2      __wdtc.bits.__ws2
#define _we0      __wdtc.bits.__we0
#define _we1      __wdtc.bits.__we1
#define _we2      __wdtc.bits.__we2
#define _we3      __wdtc.bits.__we3
#define _we4      __wdtc.bits.__we4
#define _int0s0   __integ0.bits.__int0s0
#define _int0s1   __integ0.bits.__int0s1
#define _int1s0   __integ0.bits.__int1s0
#define _int1s1   __integ0.bits.__int1s1
#define _int2s0   __integ0.bits.__int2s0
#define _int2s1   __integ0.bits.__int2s1
#define _int3s0   __integ0.bits.__int3s0
#define _int3s1   __integ0.bits.__int3s1
#define _emi      __intc0.bits.__emi
#define _int0e    __intc0.bits.__int0e
#define _int1e    __intc0.bits.__int1e
#define _ade      __intc0.bits.__ade
#define _int0f    __intc0.bits.__int0f
#define _int1f    __intc0.bits.__int1f
#define _adf      __intc0.bits.__adf
#define _mf0e     __intc1.bits.__mf0e
#define _mf1e     __intc1.bits.__mf1e
#define _mf2e     __intc1.bits.__mf2e
#define _ovpe     __intc1.bits.__ovpe
#define _mf0f     __intc1.bits.__mf0f
#define _mf1f     __intc1.bits.__mf1f
#define _mf2f     __intc1.bits.__mf2f
#define _ovpf     __intc1.bits.__ovpf
#define _tb0e     __intc2.bits.__tb0e
#define _tb1e     __intc2.bits.__tb1e
#define _int2e    __intc2.bits.__int2e
#define _int3e    __intc2.bits.__int3e
#define _tb0f     __intc2.bits.__tb0f
#define _tb1f     __intc2.bits.__tb1f
#define _int2f    __intc2.bits.__int2f
#define _int3f    __intc2.bits.__int3f
#define _ur0e     __intc3.bits.__ur0e
#define _sime     __intc3.bits.__sime
#define _spie     __intc3.bits.__spie
#define _ur1e     __intc3.bits.__ur1e
#define _ur0f     __intc3.bits.__ur0f
#define _simf     __intc3.bits.__simf
#define _spif     __intc3.bits.__spif
#define _ur1f     __intc3.bits.__ur1f
#define _pb0      __pb.bits.__pb0
#define _pb1      __pb.bits.__pb1
#define _pb2      __pb.bits.__pb2
#define _pb3      __pb.bits.__pb3
#define _pbc0     __pbc.bits.__pbc0
#define _pbc1     __pbc.bits.__pbc1
#define _pbc2     __pbc.bits.__pbc2
#define _pbc3     __pbc.bits.__pbc3
#define _pbpu0    __pbpu.bits.__pbpu0
#define _pbpu1    __pbpu.bits.__pbpu1
#define _pbpu2    __pbpu.bits.__pbpu2
#define _pbpu3    __pbpu.bits.__pbpu3
#define _pc0      __pc.bits.__pc0
#define _pc1      __pc.bits.__pc1
#define _pc2      __pc.bits.__pc2
#define _pc3      __pc.bits.__pc3
#define _pc4      __pc.bits.__pc4
#define _pc5      __pc.bits.__pc5
#define _pc6      __pc.bits.__pc6
#define _pc7      __pc.bits.__pc7
#define _pcc0     __pcc.bits.__pcc0
#define _pcc1     __pcc.bits.__pcc1
#define _pcc2     __pcc.bits.__pcc2
#define _pcc3     __pcc.bits.__pcc3
#define _pcc4     __pcc.bits.__pcc4
#define _pcc5     __pcc.bits.__pcc5
#define _pcc6     __pcc.bits.__pcc6
#define _pcc7     __pcc.bits.__pcc7
#define _pcpu0    __pcpu.bits.__pcpu0
#define _pcpu1    __pcpu.bits.__pcpu1
#define _pcpu2    __pcpu.bits.__pcpu2
#define _pcpu3    __pcpu.bits.__pcpu3
#define _pcpu4    __pcpu.bits.__pcpu4
#define _pcpu5    __pcpu.bits.__pcpu5
#define _pcpu6    __pcpu.bits.__pcpu6
#define _pcpu7    __pcpu.bits.__pcpu7
#define _int4s0   __integ1.bits.__int4s0
#define _int4s1   __integ1.bits.__int4s1
#define _int5s0   __integ1.bits.__int5s0
#define _int5s1   __integ1.bits.__int5s1
#define _clksel0  __pscr.bits.__clksel0
#define _clksel1  __pscr.bits.__clksel1
#define _tb00     __tb0c.bits.__tb00
#define _tb01     __tb0c.bits.__tb01
#define _tb02     __tb0c.bits.__tb02
#define _tb0on    __tb0c.bits.__tb0on
#define _tb10     __tb1c.bits.__tb10
#define _tb11     __tb1c.bits.__tb11
#define _tb12     __tb1c.bits.__tb12
#define _tb1on    __tb1c.bits.__tb1on
#define _txif0    __u0sr.bits.__txif0
#define _tidle0   __u0sr.bits.__tidle0
#define _rxif0    __u0sr.bits.__rxif0
#define _ridle0   __u0sr.bits.__ridle0
#define _oerr0    __u0sr.bits.__oerr0
#define _ferr0    __u0sr.bits.__ferr0
#define _nf0      __u0sr.bits.__nf0
#define _perr0    __u0sr.bits.__perr0
#define _tx80     __u0cr1.bits.__tx80
#define _rx80     __u0cr1.bits.__rx80
#define _txbrk0   __u0cr1.bits.__txbrk0
#define _stops0   __u0cr1.bits.__stops0
#define _prt0     __u0cr1.bits.__prt0
#define _pren0    __u0cr1.bits.__pren0
#define _bno0     __u0cr1.bits.__bno0
#define _uarten0  __u0cr1.bits.__uarten0
#define _teie0    __u0cr2.bits.__teie0
#define _tiie0    __u0cr2.bits.__tiie0
#define _rie0     __u0cr2.bits.__rie0
#define _wake0    __u0cr2.bits.__wake0
#define _adden0   __u0cr2.bits.__adden0
#define _brgh0    __u0cr2.bits.__brgh0
#define _rxen0    __u0cr2.bits.__rxen0
#define _txen0    __u0cr2.bits.__txen0
#define _txrx00   __txr_rxr0.bits.__txrx00
#define _txrx01   __txr_rxr0.bits.__txrx01
#define _txrx02   __txr_rxr0.bits.__txrx02
#define _txrx03   __txr_rxr0.bits.__txrx03
#define _txrx04   __txr_rxr0.bits.__txrx04
#define _txrx0    __txr_rxr0.bits.__txrx0
#define _txrx06   __txr_rxr0.bits.__txrx06
#define _txrx07   __txr_rxr0.bits.__txrx07
#define _brg00    __brg0.bits.__brg00
#define _brg01    __brg0.bits.__brg01
#define _brg02    __brg0.bits.__brg02
#define _brg03    __brg0.bits.__brg03
#define _brg04    __brg0.bits.__brg04
#define _brg05    __brg0.bits.__brg05
#define _brg06    __brg0.bits.__brg06
#define _brg07    __brg0.bits.__brg07
#define _simicf   __simc0.bits.__simicf
#define _simen    __simc0.bits.__simen
#define _simdeb0  __simc0.bits.__simdeb0
#define _simdeb1  __simc0.bits.__simdeb1
#define _sim0     __simc0.bits.__sim0
#define _sim1     __simc0.bits.__sim1
#define _sim2     __simc0.bits.__sim2
#define _rxak     __simc1.bits.__rxak
#define _iamwu    __simc1.bits.__iamwu
#define _srw      __simc1.bits.__srw
#define _txak     __simc1.bits.__txak
#define _htx      __simc1.bits.__htx
#define _hbb      __simc1.bits.__hbb
#define _haas     __simc1.bits.__haas
#define _hcf      __simc1.bits.__hcf
#define _sima0    __sima.bits.__sima0
#define _sima1    __sima.bits.__sima1
#define _sima2    __sima.bits.__sima2
#define _sima3    __sima.bits.__sima3
#define _sima4    __sima.bits.__sima4
#define _sima5    __sima.bits.__sima5
#define _sima6    __sima.bits.__sima6
#define _trf      __simc2.bits.__trf
#define _wcol     __simc2.bits.__wcol
#define _csen     __simc2.bits.__csen
#define _mls      __simc2.bits.__mls
#define _ckeg     __simc2.bits.__ckeg
#define _ckpolb   __simc2.bits.__ckpolb
#define _simtos0  __simtoc.bits.__simtos0
#define _simtos1  __simtoc.bits.__simtos1
#define _simtos2  __simtoc.bits.__simtos2
#define _simtos3  __simtoc.bits.__simtos3
#define _simtos4  __simtoc.bits.__simtos4
#define _simtos5  __simtoc.bits.__simtos5
#define _simtof   __simtoc.bits.__simtof
#define _simtoen  __simtoc.bits.__simtoen
#define _spiicf   __spic0.bits.__spiicf
#define _spien    __spic0.bits.__spien
#define _spim0    __spic0.bits.__spim0
#define _spim1    __spic0.bits.__spim1
#define _spim2    __spic0.bits.__spim2
#define _spitrf   __spic1.bits.__spitrf
#define _spiwcol  __spic1.bits.__spiwcol
#define _spicsen  __spic1.bits.__spicsen
#define _spimls   __spic1.bits.__spimls
#define _spickeg  __spic1.bits.__spickeg
#define _spickpolb __spic1.bits.__spickpolb
#define _ovpdeb0  __ovpc0.bits.__ovpdeb0
#define _ovpdeb1  __ovpc0.bits.__ovpdeb1
#define _ovpvrs   __ovpc0.bits.__ovpvrs
#define _ovpchy   __ovpc0.bits.__ovpchy
#define _ovpen    __ovpc0.bits.__ovpen
#define _ovpcof0  __ovpc1.bits.__ovpcof0
#define _ovpcof1  __ovpc1.bits.__ovpcof1
#define _ovpcof2  __ovpc1.bits.__ovpcof2
#define _ovpcof3  __ovpc1.bits.__ovpcof3
#define _ovpcof4  __ovpc1.bits.__ovpcof4
#define _ovpcrs   __ovpc1.bits.__ovpcrs
#define _ovpcofm  __ovpc1.bits.__ovpcofm
#define _ovpo     __ovpc1.bits.__ovpo
#define _eea0     __eea.bits.__eea0
#define _eea1     __eea.bits.__eea1
#define _eea2     __eea.bits.__eea2
#define _eea3     __eea.bits.__eea3
#define _eea4     __eea.bits.__eea4
#define _eea5     __eea.bits.__eea5
#define _eea6     __eea.bits.__eea6
#define _txif1    __u1sr.bits.__txif1
#define _tidle1   __u1sr.bits.__tidle1
#define _rxif1    __u1sr.bits.__rxif1
#define _ridle1   __u1sr.bits.__ridle1
#define _oerr1    __u1sr.bits.__oerr1
#define _ferr1    __u1sr.bits.__ferr1
#define _nf1      __u1sr.bits.__nf1
#define _perr1    __u1sr.bits.__perr1
#define _tx81     __u1cr1.bits.__tx81
#define _rx81     __u1cr1.bits.__rx81
#define _txbrk1   __u1cr1.bits.__txbrk1
#define _stops1   __u1cr1.bits.__stops1
#define _prt1     __u1cr1.bits.__prt1
#define _pren1    __u1cr1.bits.__pren1
#define _bno1     __u1cr1.bits.__bno1
#define _uarten1  __u1cr1.bits.__uarten1
#define _teie1    __u1cr2.bits.__teie1
#define _tiie1    __u1cr2.bits.__tiie1
#define _rie1     __u1cr2.bits.__rie1
#define _wake1    __u1cr2.bits.__wake1
#define _adden1   __u1cr2.bits.__adden1
#define _brgh1    __u1cr2.bits.__brgh1
#define _rxen1    __u1cr2.bits.__rxen1
#define _txen1    __u1cr2.bits.__txen1
#define _txrx10   __txr_rxr1.bits.__txrx10
#define _txrx11   __txr_rxr1.bits.__txrx11
#define _txrx12   __txr_rxr1.bits.__txrx12
#define _txrx13   __txr_rxr1.bits.__txrx13
#define _txrx14   __txr_rxr1.bits.__txrx14
#define _txrx15   __txr_rxr1.bits.__txrx15
#define _txrx16   __txr_rxr1.bits.__txrx16
#define _txrx17   __txr_rxr1.bits.__txrx17
#define _brg10    __brg1.bits.__brg10
#define _brg11    __brg1.bits.__brg11
#define _brg12    __brg1.bits.__brg12
#define _brg13    __brg1.bits.__brg13
#define _brg14    __brg1.bits.__brg14
#define _brg15    __brg1.bits.__brg15
#define _brg16    __brg1.bits.__brg16
#define _brg17    __brg1.bits.__brg17
#define _ston     __stmc0.bits.__ston
#define _stck0    __stmc0.bits.__stck0
#define _stck1    __stmc0.bits.__stck1
#define _stck2    __stmc0.bits.__stck2
#define _stpau    __stmc0.bits.__stpau
#define _stcclr   __stmc1.bits.__stcclr
#define _stdpx    __stmc1.bits.__stdpx
#define _stpol    __stmc1.bits.__stpol
#define _stoc     __stmc1.bits.__stoc
#define _stio0    __stmc1.bits.__stio0
#define _stio1    __stmc1.bits.__stio1
#define _stm0     __stmc1.bits.__stm0
#define _stm1     __stmc1.bits.__stm1
#define _pt0on    __ptm0c0.bits.__pt0on
#define _pt0ck0   __ptm0c0.bits.__pt0ck0
#define _pt0ck1   __ptm0c0.bits.__pt0ck1
#define _pt0ck2   __ptm0c0.bits.__pt0ck2
#define _pt0pau   __ptm0c0.bits.__pt0pau
#define _pt0cclr  __ptm0c1.bits.__pt0cclr
#define _pt0capts __ptm0c1.bits.__pt0capts
#define _pt0pol   __ptm0c1.bits.__pt0pol
#define _pt0oc    __ptm0c1.bits.__pt0oc
#define _pt0io0   __ptm0c1.bits.__pt0io0
#define _pt0io1   __ptm0c1.bits.__pt0io1
#define _pt0m0    __ptm0c1.bits.__pt0m0
#define _pt0m1    __ptm0c1.bits.__pt0m1
#define _mdwov    __mduwctrl.bits.__mdwov
#define _mdwef    __mduwctrl.bits.__mdwef
#define _pgas0    __pgac0.bits.__pgas0
#define _pgas1    __pgac0.bits.__pgas1
#define _pgas2    __pgac0.bits.__pgas2
#define _ags0     __pgac0.bits.__ags0
#define _ags1     __pgac0.bits.__ags1
#define _vgs0     __pgac0.bits.__vgs0
#define _vgs1     __pgac0.bits.__vgs1
#define _pgabp    __pgac0.bits.__pgabp
#define _dcset0   __pgac1.bits.__dcset0
#define _dcset1   __pgac1.bits.__dcset1
#define _dcset2   __pgac1.bits.__dcset2
#define _inx0     __pgac1.bits.__inx0
#define _inx1     __pgac1.bits.__inx1
#define _inis     __pgac1.bits.__inis
#define _pgabpbuf __pgac1.bits.__pgabpbuf
#define _chsp0    __pgacs.bits.__chsp0
#define _chsp1    __pgacs.bits.__chsp1
#define _chsp2    __pgacs.bits.__chsp2
#define _chsp3    __pgacs.bits.__chsp3
#define _chsn0    __pgacs.bits.__chsn0
#define _chsn1    __pgacs.bits.__chsn1
#define _chsn2    __pgacs.bits.__chsn2
#define _chsn3    __pgacs.bits.__chsn3
#define _ador0    __adcr0.bits.__ador0
#define _ador1    __adcr0.bits.__ador1
#define _ador2    __adcr0.bits.__ador2
#define _adoff    __adcr0.bits.__adoff
#define _adslp    __adcr0.bits.__adslp
#define _adrst    __adcr0.bits.__adrst
#define _eoc      __adcr1.bits.__eoc
#define _adcdl    __adcr1.bits.__adcdl
#define _flms0    __adcr1.bits.__flms0
#define _flms1    __adcr1.bits.__flms1
#define _flms2    __adcr1.bits.__flms2
#define _adck0    __adcs.bits.__adck0
#define _adck1    __adcs.bits.__adck1
#define _adck2    __adcs.bits.__adck2
#define _adck3    __adcs.bits.__adck3
#define _adck4    __adcs.bits.__adck4
#define _ldovs0   __pwrc.bits.__ldovs0
#define _ldovs1   __pwrc.bits.__ldovs1
#define _ldobps   __pwrc.bits.__ldobps
#define _ldoen    __pwrc.bits.__ldoen
#define _dacvrs0  __irefc.bits.__dacvrs0
#define _dacvrs1  __irefc.bits.__dacvrs1
#define _irefen   __irefc.bits.__irefen
#define _op2do    __irefc.bits.__op2do
#define _op1do    __irefc.bits.__op1do
#define _opa1of0  __opa1c.bits.__opa1of0
#define _opa1of1  __opa1c.bits.__opa1of1
#define _opa1of2  __opa1c.bits.__opa1of2
#define _opa1of3  __opa1c.bits.__opa1of3
#define _opa1of4  __opa1c.bits.__opa1of4
#define _opa1en   __opa1c.bits.__opa1en
#define _opa1rs   __opa1c.bits.__opa1rs
#define _opa1ofm  __opa1c.bits.__opa1ofm
#define _opa2of0  __opa2c.bits.__opa2of0
#define _opa2of1  __opa2c.bits.__opa2of1
#define _opa2of2  __opa2c.bits.__opa2of2
#define _opa2of3  __opa2c.bits.__opa2of3
#define _opa2of4  __opa2c.bits.__opa2of4
#define _opa2en   __opa2c.bits.__opa2en
#define _opa2rs   __opa2c.bits.__opa2rs
#define _opa2ofm  __opa2c.bits.__opa2ofm
#define _gsw0     __gsc1.bits.__gsw0
#define _gsw1     __gsc1.bits.__gsw1
#define _gsw4     __gsc1.bits.__gsw4
#define _gsw5     __gsc1.bits.__gsw5
#define _gsw6     __gsc1.bits.__gsw6
#define _gsw7     __gsc1.bits.__gsw7
#define _gsvg00   __gsc2.bits.__gsvg00
#define _gsvg01   __gsc2.bits.__gsvg01
#define _gsvg02   __gsc2.bits.__gsvg02
#define _gsvg10   __gsc2.bits.__gsvg10
#define _gsvg11   __gsc2.bits.__gsvg11
#define _gsvg12   __gsc2.bits.__gsvg12
#define _gsw8     __gsc2.bits.__gsw8
#define _gsw9     __gsc2.bits.__gsw9
#define _gsop1p0  __gsc3.bits.__gsop1p0
#define _gsop1p1  __gsc3.bits.__gsop1p1
#define _gsop2p0  __gsc3.bits.__gsop2p0
#define _gsop2p1  __gsc3.bits.__gsop2p1
#define _afeda1cm0 __afeda1c.bits.__afeda1cm0
#define _afeda1cm1 __afeda1c.bits.__afeda1cm1
#define _afeda2cm0 __afeda2c.bits.__afeda2cm0
#define _afeda2cm1 __afeda2c.bits.__afeda2cm1
#define _sgiqrs   __sgc.bits.__sgiqrs
#define _sgop0p0  __sgc.bits.__sgop0p0
#define _sgop0p1  __sgc.bits.__sgop0p1
#define _bren     __sgc.bits.__bren
#define _sgen     __sgc.bits.__sgen
#define _op4g0    __bopac0.bits.__op4g0
#define _op4g1    __bopac0.bits.__op4g1
#define _op4g2    __bopac0.bits.__op4g2
#define _op4g3    __bopac0.bits.__op4g3
#define _op3do    __bopac0.bits.__op3do
#define _iq_fwr   __bopac0.bits.__iq_fwr
#define _bopaen   __bopac0.bits.__bopaen
#define _opa3of0  __bopac1.bits.__opa3of0
#define _opa3of1  __bopac1.bits.__opa3of1
#define _opa3of2  __bopac1.bits.__opa3of2
#define _opa3of3  __bopac1.bits.__opa3of3
#define _opa3of4  __bopac1.bits.__opa3of4
#define _opa3en   __bopac1.bits.__opa3en
#define _opa3rs   __bopac1.bits.__opa3rs
#define _opa3ofm  __bopac1.bits.__opa3ofm
#define _bsw0     __bswc0.bits.__bsw0
#define _bsw1     __bswc0.bits.__bsw1
#define _bsw2     __bswc0.bits.__bsw2
#define _bsw3     __bswc0.bits.__bsw3
#define _bsw4     __bswc0.bits.__bsw4
#define _bsw5     __bswc0.bits.__bsw5
#define _bsw6     __bswc0.bits.__bsw6
#define _bsw7     __bswc0.bits.__bsw7
#define _bsw8     __bswc1.bits.__bsw8
#define _bsw9     __bswc1.bits.__bsw9
#define _bswsino1 __bswc2.bits.__bswsino1
#define _bswsino2 __bswc2.bits.__bswsino2
#define _bswsini  __bswc2.bits.__bswsini
#define _bswrf1   __bswc2.bits.__bswrf1
#define _bswrf2   __bswc2.bits.__bswrf2
#define _pt1on    __ptm1c0.bits.__pt1on
#define _pt1ck0   __ptm1c0.bits.__pt1ck0
#define _pt1ck1   __ptm1c0.bits.__pt1ck1
#define _pt1ck2   __ptm1c0.bits.__pt1ck2
#define _pt1pau   __ptm1c0.bits.__pt1pau
#define _pt1cclr  __ptm1c1.bits.__pt1cclr
#define _pt1capts __ptm1c1.bits.__pt1capts
#define _pt1pol   __ptm1c1.bits.__pt1pol
#define _pt1oc    __ptm1c1.bits.__pt1oc
#define _pt1io0   __ptm1c1.bits.__pt1io0
#define _pt1io1   __ptm1c1.bits.__pt1io1
#define _pt1m0    __ptm1c1.bits.__pt1m0
#define _pt1m1    __ptm1c1.bits.__pt1m1
#define _pt2on    __ptm2c0.bits.__pt2on
#define _pt2ck0   __ptm2c0.bits.__pt2ck0
#define _pt2ck1   __ptm2c0.bits.__pt2ck1
#define _pt2ck2   __ptm2c0.bits.__pt2ck2
#define _pt2pau   __ptm2c0.bits.__pt2pau
#define _pt2cclr  __ptm2c1.bits.__pt2cclr
#define _pt2capts __ptm2c1.bits.__pt2capts
#define _pt2pol   __ptm2c1.bits.__pt2pol
#define _pt2oc    __ptm2c1.bits.__pt2oc
#define _pt2io0   __ptm2c1.bits.__pt2io0
#define _pt2io1   __ptm2c1.bits.__pt2io1
#define _pt2m0    __ptm2c1.bits.__pt2m0
#define _pt2m1    __ptm2c1.bits.__pt2m1
#define _lcden    __lcdc0.bits.__lcden
#define _lcdis0   __lcdc0.bits.__lcdis0
#define _lcdis1   __lcdc0.bits.__lcdis1
#define _lcdp0    __lcdc0.bits.__lcdp0
#define _lcdp1    __lcdc0.bits.__lcdp1
#define _rct      __lcdc0.bits.__rct
#define _type     __lcdc0.bits.__type
#define _cpvs0    __lcdcp.bits.__cpvs0
#define _cpvs1    __lcdcp.bits.__cpvs1
#define _lcdpr    __lcdcp.bits.__lcdpr
#define _bias     __lcdc2.bits.__bias
#define _dtyc0    __lcdc2.bits.__dtyc0
#define _dtyc1    __lcdc2.bits.__dtyc1
#define _lcdpck0  __lcdc2.bits.__lcdpck0
#define _lcdpck1  __lcdc2.bits.__lcdpck1
#define _lcdpck2  __lcdc2.bits.__lcdpck2
#define _pd0      __pd.bits.__pd0
#define _pd1      __pd.bits.__pd1
#define _pd2      __pd.bits.__pd2
#define _pd3      __pd.bits.__pd3
#define _pd4      __pd.bits.__pd4
#define _pd5      __pd.bits.__pd5
#define _pd6      __pd.bits.__pd6
#define _pdc0     __pdc.bits.__pdc0
#define _pdc1     __pdc.bits.__pdc1
#define _pdc2     __pdc.bits.__pdc2
#define _pdc3     __pdc.bits.__pdc3
#define _pdc4     __pdc.bits.__pdc4
#define _pdc5     __pdc.bits.__pdc5
#define _pdc6     __pdc.bits.__pdc6
#define _pdpu0    __pdpu.bits.__pdpu0
#define _pdpu1    __pdpu.bits.__pdpu1
#define _pdpu2    __pdpu.bits.__pdpu2
#define _pdpu3    __pdpu.bits.__pdpu3
#define _pdpu4    __pdpu.bits.__pdpu4
#define _pdpu5    __pdpu.bits.__pdpu5
#define _pdpu6    __pdpu.bits.__pdpu6
#define _pe0      __pe.bits.__pe0
#define _pe1      __pe.bits.__pe1
#define _pe2      __pe.bits.__pe2
#define _pe3      __pe.bits.__pe3
#define _pe4      __pe.bits.__pe4
#define _pe5      __pe.bits.__pe5
#define _pe6      __pe.bits.__pe6
#define _pe7      __pe.bits.__pe7
#define _pec0     __pec.bits.__pec0
#define _pec1     __pec.bits.__pec1
#define _pec2     __pec.bits.__pec2
#define _pec3     __pec.bits.__pec3
#define _pec4     __pec.bits.__pec4
#define _pec5     __pec.bits.__pec5
#define _pec6     __pec.bits.__pec6
#define _pec7     __pec.bits.__pec7
#define _pepu0    __pepu.bits.__pepu0
#define _pepu1    __pepu.bits.__pepu1
#define _pepu2    __pepu.bits.__pepu2
#define _pepu3    __pepu.bits.__pepu3
#define _pepu4    __pepu.bits.__pepu4
#define _pepu5    __pepu.bits.__pepu5
#define _pepu6    __pepu.bits.__pepu6
#define _pepu7    __pepu.bits.__pepu7
#define _pf0      __pf.bits.__pf0
#define _pf1      __pf.bits.__pf1
#define _pf2      __pf.bits.__pf2
#define _pf3      __pf.bits.__pf3
#define _pf4      __pf.bits.__pf4
#define _pf5      __pf.bits.__pf5
#define _pf6      __pf.bits.__pf6
#define _pf7      __pf.bits.__pf7
#define _pfc0     __pfc.bits.__pfc0
#define _pfc1     __pfc.bits.__pfc1
#define _pfc2     __pfc.bits.__pfc2
#define _pfc3     __pfc.bits.__pfc3
#define _pfc4     __pfc.bits.__pfc4
#define _pfc5     __pfc.bits.__pfc5
#define _pfc6     __pfc.bits.__pfc6
#define _pfc7     __pfc.bits.__pfc7
#define _pfpu0    __pfpu.bits.__pfpu0
#define _pfpu1    __pfpu.bits.__pfpu1
#define _pfpu2    __pfpu.bits.__pfpu2
#define _pfpu3    __pfpu.bits.__pfpu3
#define _pfpu4    __pfpu.bits.__pfpu4
#define _pfpu5    __pfpu.bits.__pfpu5
#define _pfpu6    __pfpu.bits.__pfpu6
#define _pfpu7    __pfpu.bits.__pfpu7
#define _pg0      __pg.bits.__pg0
#define _pg1      __pg.bits.__pg1
#define _pg2      __pg.bits.__pg2
#define _pgc0     __pgc.bits.__pgc0
#define _pgc1     __pgc.bits.__pgc1
#define _pgc2     __pgc.bits.__pgc2
#define _pgpu0    __pgpu.bits.__pgpu0
#define _pgpu1    __pgpu.bits.__pgpu1
#define _pgpu2    __pgpu.bits.__pgpu2
#define _rd       __eec.bits.__rd
#define _rden     __eec.bits.__rden
#define _wr       __eec.bits.__wr
#define _wren     __eec.bits.__wren
#define _frd      __fc0.bits.__frd
#define _frden    __fc0.bits.__frden
#define _fwt      __fc0.bits.__fwt
#define _fwpen    __fc0.bits.__fwpen
#define _fmod0    __fc0.bits.__fmod0
#define _fmod1    __fc0.bits.__fmod1
#define _fmod2    __fc0.bits.__fmod2
#define _cfwen    __fc0.bits.__cfwen
#define _clwb     __fc2.bits.__clwb
#define _fa0      __farl.bits.__fa0
#define _fa1      __farl.bits.__fa1
#define _fa2      __farl.bits.__fa2
#define _fa3      __farl.bits.__fa3
#define _fa4      __farl.bits.__fa4
#define _fa5      __farl.bits.__fa5
#define _fa6      __farl.bits.__fa6
#define _fa7      __farl.bits.__fa7
#define _fa8      __farh.bits.__fa8
#define _fa9      __farh.bits.__fa9
#define _fa10     __farh.bits.__fa10
#define _fa11     __farh.bits.__fa11
#define _fa12     __farh.bits.__fa12
#define _fa13     __farh.bits.__fa13
#define _fa14     __farh.bits.__fa14
#define _fa15     __farh.bits.__fa15
#define _stckps   __ifs0.bits.__stckps
#define _ptck2ps  __ifs0.bits.__ptck2ps
#define _ptp0ips  __ifs0.bits.__ptp0ips
#define _ptp1ips  __ifs0.bits.__ptp1ips
#define _ptp2ips  __ifs0.bits.__ptp2ips
#define _spisckps __ifs1.bits.__spisckps
#define _spisdips __ifs1.bits.__spisdips
#define _spiscsbps __ifs1.bits.__spiscsbps
#define _pas00    __pas0.bits.__pas00
#define _pas01    __pas0.bits.__pas01
#define _pas02    __pas0.bits.__pas02
#define _pas03    __pas0.bits.__pas03
#define _pas04    __pas0.bits.__pas04
#define _pas05    __pas0.bits.__pas05
#define _pas06    __pas0.bits.__pas06
#define _pas07    __pas0.bits.__pas07
#define _pas10    __pas1.bits.__pas10
#define _pas11    __pas1.bits.__pas11
#define _pas12    __pas1.bits.__pas12
#define _pas13    __pas1.bits.__pas13
#define _pas14    __pas1.bits.__pas14
#define _pas15    __pas1.bits.__pas15
#define _pas16    __pas1.bits.__pas16
#define _pas17    __pas1.bits.__pas17
#define _pbs00    __pbs0.bits.__pbs00
#define _pbs01    __pbs0.bits.__pbs01
#define _pbs02    __pbs0.bits.__pbs02
#define _pbs03    __pbs0.bits.__pbs03
#define _pbs04    __pbs0.bits.__pbs04
#define _pbs05    __pbs0.bits.__pbs05
#define _pbs06    __pbs0.bits.__pbs06
#define _pbs07    __pbs0.bits.__pbs07
#define _pcs00    __pcs0.bits.__pcs00
#define _pcs01    __pcs0.bits.__pcs01
#define _pcs02    __pcs0.bits.__pcs02
#define _pcs03    __pcs0.bits.__pcs03
#define _pcs04    __pcs0.bits.__pcs04
#define _pcs05    __pcs0.bits.__pcs05
#define _pcs06    __pcs0.bits.__pcs06
#define _pcs07    __pcs0.bits.__pcs07
#define _pcs10    __pcs1.bits.__pcs10
#define _pcs11    __pcs1.bits.__pcs11
#define _pcs12    __pcs1.bits.__pcs12
#define _pcs13    __pcs1.bits.__pcs13
#define _pds00    __pds0.bits.__pds00
#define _pds01    __pds0.bits.__pds01
#define _pds02    __pds0.bits.__pds02
#define _pds03    __pds0.bits.__pds03
#define _pds04    __pds0.bits.__pds04
#define _pds05    __pds0.bits.__pds05
#define _pds06    __pds0.bits.__pds06
#define _pds07    __pds0.bits.__pds07
#define _pds10    __pds1.bits.__pds10
#define _pds11    __pds1.bits.__pds11
#define _pds12    __pds1.bits.__pds12
#define _pds13    __pds1.bits.__pds13
#define _pds14    __pds1.bits.__pds14
#define _pds15    __pds1.bits.__pds15
#define _pes00    __pes0.bits.__pes00
#define _pes01    __pes0.bits.__pes01
#define _pes02    __pes0.bits.__pes02
#define _pes03    __pes0.bits.__pes03
#define _pes04    __pes0.bits.__pes04
#define _pes05    __pes0.bits.__pes05
#define _pes06    __pes0.bits.__pes06
#define _pes07    __pes0.bits.__pes07
#define _pes10    __pes1.bits.__pes10
#define _pes11    __pes1.bits.__pes11
#define _pes12    __pes1.bits.__pes12
#define _pes13    __pes1.bits.__pes13
#define _pes14    __pes1.bits.__pes14
#define _pes15    __pes1.bits.__pes15
#define _pes16    __pes1.bits.__pes16
#define _pes17    __pes1.bits.__pes17
#define _pfs00    __pfs0.bits.__pfs00
#define _pfs01    __pfs0.bits.__pfs01
#define _pfs02    __pfs0.bits.__pfs02
#define _pfs03    __pfs0.bits.__pfs03
#define _pfs04    __pfs0.bits.__pfs04
#define _pfs05    __pfs0.bits.__pfs05
#define _pfs06    __pfs0.bits.__pfs06
#define _pfs07    __pfs0.bits.__pfs07
#define _pfs10    __pfs1.bits.__pfs10
#define _pfs11    __pfs1.bits.__pfs11
#define _pfs12    __pfs1.bits.__pfs12
#define _pfs13    __pfs1.bits.__pfs13
#define _pfs14    __pfs1.bits.__pfs14
#define _pfs15    __pfs1.bits.__pfs15
#define _pfs16    __pfs1.bits.__pfs16
#define _pfs17    __pfs1.bits.__pfs17
#define _pgs00    __pgs0.bits.__pgs00
#define _pgs01    __pgs0.bits.__pgs01
#define _pgs02    __pgs0.bits.__pgs02
#define _pgs03    __pgs0.bits.__pgs03
#define _pgs04    __pgs0.bits.__pgs04
#define _pgs05    __pgs0.bits.__pgs05
#define _sledc00  __sledc0.bits.__sledc00
#define _sledc01  __sledc0.bits.__sledc01
#define _sledc02  __sledc0.bits.__sledc02
#define _sledc03  __sledc0.bits.__sledc03
#define _sledc04  __sledc0.bits.__sledc04
#define _sledc05  __sledc0.bits.__sledc05
#define _sledc10  __sledc1.bits.__sledc10
#define _sledc11  __sledc1.bits.__sledc11
#define _sledc12  __sledc1.bits.__sledc12
#define _sledc13  __sledc1.bits.__sledc13
#define _sledc14  __sledc1.bits.__sledc14
#define _sledc15  __sledc1.bits.__sledc15
#define _sledc16  __sledc1.bits.__sledc16
#define _sledc17  __sledc1.bits.__sledc17
#define _sledc20  __sledc2.bits.__sledc20
#define _sledc21  __sledc2.bits.__sledc21
#define _sledc22  __sledc2.bits.__sledc22
#define _sledc23  __sledc2.bits.__sledc23
#define _sledc24  __sledc2.bits.__sledc24
#define _sledc25  __sledc2.bits.__sledc25
#define _sledc26  __sledc2.bits.__sledc26
#define _sledc27  __sledc2.bits.__sledc27
#define _sledc30  __sledc3.bits.__sledc30
#define _sledc31  __sledc3.bits.__sledc31

#define ___mkstr(x)                #x
#define __EEPROM_DATA(a, b, c, d, e, f, g, h) \
                         asm("eeprom_data .section 'eeprom'"); \
                         asm("db\t" ___mkstr(a));        \
                         asm("db\t" ___mkstr(b));        \
                         asm("db\t" ___mkstr(c));        \
                         asm("db\t" ___mkstr(d));        \
                         asm("db\t" ___mkstr(e));        \
                         asm("db\t" ___mkstr(f));        \
                         asm("db\t" ___mkstr(g));        \
                         asm("db\t" ___mkstr(h));        

#endif // _BH67F2485_H_
