
#include "BH67F2485.h"
//#include "stdio.h "
#include "flag.h"
#include "flash.h"
#include "string.h"
#include "math.h"
#include "stdlib.h"

//#include "flash.h"
#include "define.h"
#include "variable.h"
//#include  "config.h"
#include "eeprom.h"
#include  "uart.h"
//#include "codecard.h"
#include  "math.h"
#include  "AFEADC.h"
#include  "AFEOPA.h"
#include  "AFEPower.h"
#include  "AFESineWave.h"
#include  "typedef.h"
#include  "iap.h"

#include "option.h"
#include "LcdScan.h"
#include "lcd2.h"
#include "codecard.h"
#include "uart2.h"
#include "gsm.h"

